### ISSUE TITLE
Anzeige überlappt in Safari

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#108]
**Describe the bug**
Die einzelnen Zeilen werden überlappend angezeigt und der Abstand dawischen ist manchmal zu groß. 

**To Reproduce**
1. Go to 'Zugsuche'

**Screenshots**
<img width="1349" alt="Bildschirmfoto 2019-11-02 um 18 17 58" src="https://user-images.githubusercontent.com/11199213/68074766-268e5400-fd9f-11e9-9474-4db92d5957ed.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser Safari
 - Version 12.0.3

**Additional context**
Tritt nur bei der Desktop-Version von Safari auf.

**Comment by marudor** [comment]
I've tried a lot to reproduce it. But sadly I wasn't able so far.
If you encounter it again could you send me a message via twitter? (Maybe it's related to specific data?)

I've tried Safari 12.0.3 with macOS Catalina - but that shouldn't matter.

**Comment by marudor** [comment]
Nach Rücksprachen geschlossen.
Absolut nicht reproduzierbar. Wenn doch neues.
