### ISSUE TITLE
Can't choose backends except default Favendo

### ISSUE THREAD

**Issue by bridgerdier** [marudor/BahnhofsAbfahrten#110]
**Describe the bug**
Current version doesn't allow choosing a backend. Existing cookies are ignored, drop-down in settings doesn't change value

**To Reproduce**
1. Go to marudor.de/Bonn UN Campus
2. "Unexpected error"

**Expected behavior**
Abfahrtstafel

**Desktop (please complete the following information):**
 - OS: Linux/KDE
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Nokia 7 Plus
 - OS: Android 9
 - Browser Chrome
 - Version current

**Comment by marudor** [comment]
Already fixed
