### ISSUE TITLE
zusätzliche Datenquelle strecken.info

### ISSUE THREAD

**Issue by mm-chen** [marudor/BahnhofsAbfahrten#114]
Mögliche Behinderungen die meinen Zug/ meine Verbindung betreffen, könnten durch Ereignisse auf der Strecke erklärt sein. Strecken.info liefert unter anderem CSV-Dateien die Störungen an der Strecke anzeigen.

**Comment by derhuerst** [comment]
FYI es gibt auch [`db-netz-hafas`](https://github.com/derhuerst/db-netz-hafas), falls die CSV-Dateien nicht alles abdecken.
