### ISSUE TITLE
Kompatibilität als “Web App”

### ISSUE THREAD

**Issue by Knuspel** [marudor/BahnhofsAbfahrten#137]
**Is your feature request related to a problem? Please describe.**
Wenn die Webseite auf iOS als Webapp gespeichert wird, dann scrollt sie hinter dem Header entlang und macht es so unmöglich die Zeit zu lesen. 

**Describe the solution you'd like**
Ein klares Verhalten als “webapp”, so dass in der Nutzung der Webseite als solche nicht mehr auffällt, dass diese nicht nativ ist. 

**Describe alternatives you've considered**
None

**Screenshot**
![973BF00F-FA6C-4F96-95FF-658851B8C77F](https://user-images.githubusercontent.com/57443990/69918584-3cf9ff00-1474-11ea-9e39-04958cdb2bf6.jpeg)
Hier ist die Zeit zu erkennen, aber das Problem wird deutlich. Der Inhalt geht über den Header hinaus.

**Comment by marudor** [comment]
Duplicate of #42 
Currently marudor.de does not provide PWA features.
