### ISSUE TITLE
Zug wird als komplett ausfallend angezeigt, obwohl nur ein Halt entfällt

### ISSUE THREAD

**Issue by cmfcmf** [marudor/BahnhofsAbfahrten#138]
**Describe the bug**

Ein Zug wird als komplett ausfallend angezeigt, obwohl nur eine Station ausfällt. 
Aktuell fällt der Halt in Albrechtshof bei allen Zügen aus. Unter https://marudor.de/Albrechtshof wirkt es aber so, als würde der komplette Zug ausfallen, und nicht nur der Halt in Albrechtshof. Auf der Detailseite des Zuges sieht es widerum richtig aus, dort ist nur der Halt in Albrechtshof als Ausfall gekennzeichnet. Ebenfalls richtig sieht es aus, wenn man die Abfahrtstafel für Seegefeld, den Halt davor, aufruft: https://marudor.de/Seegefeld. Dort wird nur der Halt in Albrechtshof als ausfallend gekennzeichnet.

**To Reproduce**
- https://marudor.de/Albrechtshof aufrufen -> "Zugausfall", alle Halte durchgestrichen
- https://marudor.de/Seegefeld aufrufen -> Nur der Halt in Albrechtshof ist durchgestrichen

**Expected behavior**
Auch bei der Abfahrtstafel von Albrechtshof sollte nur der Halt in Albrechtshof durchgestrichen sein.

**Screenshots**

![Bildschirmfoto von 2019-12-03 10-39-13](https://user-images.githubusercontent.com/2145092/70039106-a20b3d00-15b9-11ea-97fd-095aed4d2aa3.png)
![Bildschirmfoto von 2019-12-03 10-42-50](https://user-images.githubusercontent.com/2145092/70039157-bfd8a200-15b9-11ea-8928-00b63cf1c7d8.png)
![Bildschirmfoto von 2019-12-03 10-43-06](https://user-images.githubusercontent.com/2145092/70039158-c0713880-15b9-11ea-967c-5012b229bb4e.png)

Zum Vergleich noch der Screenshot von der Bahnseite: Dort sieht man ebenfalls, dass nur der Halt in Albrechtshof entfällt, aber die Halte danach angefahren werden.
![Bildschirmfoto von 2019-12-03 10-44-14](https://user-images.githubusercontent.com/2145092/70039233-e0086100-15b9-11ea-9ca5-6cc0acfb684a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Version: 78

**Comment by marudor** [comment]
Die APIs geben das leider nicht her (Außer ich check das bei jedem einzeln)
Ich bekomm halt für den Zug gesagt er fällt komplett aus. Sonst würde ich das korrekt darstellen.

Könnte nen workaround macjen indem ich das HAFAS frage. Problem dabei: Ich müsste bei jedem Haltausfall immer das HAFAS fragen => Langsam.
Evtl als info refinement beim klick auf die Abfahrt.

**Comment by marudor** [comment]
Fixed.
