### ISSUE TITLE
Freitext-Meldungen zu Zügen ebenfalls anzeigen

### ISSUE THREAD

**Issue by cmfcmf** [marudor/BahnhofsAbfahrten#139]
**Is your feature request related to a problem? Please describe.**
Die Freitext-Meldungen zu einzelnen Zügen sind auf marudor.de nicht zu sehen. Dadurch fehlen oft wichtige Informationen: In der Bahn-Reiseauskunft stehen dort z.B. manchmal Informationen zum eingesetzten Zug ("heute nur ein vierteiliger Zug", "heute nur ein dreiteiliger Talent", ...) aber auch zu Störungen ("Bitte beachten Sie, der Halt in Albrechtshof entfällt. Grund sind die Auswirkungen des Personenunfalls. Zwischen Albrechtshof und Seegefeld pendelt ein unregelmäßiger Busnotverkehr.", ...). Es wäre praktisch, diese ebenfalls auf marudor.de zu sehen.

**Describe the solution you'd like**
Wenn die APIs das hergeben, eine Anzeige der Freitext-Meldungen bei den Zügen.

**Describe alternatives you've considered**

--

**Additional context**

Screenshots von beispielhaften Meldungen von heute: 
![Bildschirmfoto von 2019-12-03 10-58-08](https://user-images.githubusercontent.com/2145092/70040410-d08a1780-15bb-11ea-9c29-6a69611267f0.png)
![Bildschirmfoto von 2019-12-03 10-58-22](https://user-images.githubusercontent.com/2145092/70040428-d849bc00-15bb-11ea-97d4-6b2c5f27a2b1.png)

**Comment by marudor** [comment]
Momentan werden HIM Freitexte nicht geparsed. Für Texte an Stationen siehe details page.
Da sind abe auch noch keine HIM Nachrichten die an der Journey Gesamt liegen.
Bekannt. Kommt evtl mal.

**Comment by marudor** [comment]
Seit ner Weile drin. (Information/Störung/Großstörung auf der abfahrten Seite)
