### ISSUE TITLE
Mehr padding-left/right, insbesondere in der Zuglaufanzeige

### ISSUE THREAD

**Issue by bridgerdier** [marudor/BahnhofsAbfahrten#145]
**Is your feature request related to a problem? Please describe.**
Viele Informationen befinden sich am linken/rechten Bildschirmrand und wirken dort sehr gequetscht. Besonders ausgeprägt ist dies bei der Zuglaufanzeige, die im Unterschied zu den Bahnhofsabfahrten offensichtlich keinerlei Rand lässt. Besonders problematisch sind Links am linken Bildschirmrand (wie 'Details') auf Smartphones, wo stets die Gefahr besteht, unabsichtlich das Seitenmenü auszuklappen.

**Describe the solution you'd like**
Mehr Seitenabstand, mindestens beim Zuglauf auf das bei den Bahnhofsabfahrten vorhandene Maß, aber bevorzugt in beiden Fällen mehr.

**Comment by marudor** [comment]
Fixed.
