### ISSUE TITLE
Automatic switch to dark theme

### ISSUE THREAD

**Issue by rugk** [marudor/BahnhofsAbfahrten#17]
There is a quite new CSS media query feature called [`prefers-color-scheme`](https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme). It allows you to detect whether the system/user wants a dark website, so you can adjust your CSS.

Currently it is only supported by Safari and Firefox 67 or higher.

Anyway, it would be great, if you could make use of this, so you can automatically use the (one) dark mode, when the user prefers this.

BTW: I also have [a Firefox add-on called “Dark Mode Website Switcher”](https://addons.mozilla.org/de/firefox/addon/dark-mode-website-switcher/?src=external-github-issue) ([source code](https://github.com/rugk/website-dark-mode-switcher))  that you can use to toggle this setting in Firefox directly – without needing to change the system option. Maybe that could be helpful.

**Comment by marudor** [comment]
It's already in place and working.

**Comment by rugk** [comment]
Ah okay, great! :smiley:
