### ISSUE TITLE
Train number collision with SBB trains

### ISSUE THREAD

**Issue by biolauri** [marudor/BahnhofsAbfahrten#171]
I'm using the Nuremberg–Bayreuth(–Hof) line frequently and for some time, their train details are mixed up with SBB trains in the Zurich/Chur area, which have the same numbers. I think, this came up/was introduced with the approach for #146, but I can't tell that for sure.

I just tested around and found especially the numbers `RE 347*` and `RE 348*` (for example _RE 3470_ or _RE 3485_), which have the wrong details.

___

Thank you for this great app! I'm very happy with it and using it almost daily.

**Comment by marudor** [comment]
Will investigate. Yes it was introduced by the fix for #146.
