### ISSUE TITLE
UIC-Nummern kürzen

### ISSUE THREAD

**Issue by baeuchle** [marudor/BahnhofsAbfahrten#175]
**Describe the bug**
In allen Ansichten (Smartphone und Browser) überlappen die UIC-Nummern von aufeinanderfolgenden Fahrzeugen.

**To Reproduce**
1. Go to Details eines Zuges in Abfahrtstafel oder Detailseite eines Zuges, der mit ICE1 fährt.
4. Fehler tritt bei Browserfenstergrößen von kleiner als 1530Pixel bei einem ICE1 zwischen den Zwischenwagen auf; die Triebköpfe überlappen auch bei 1920px. (Mit ICE4 und doppelten ICE[23T] ist es wahrscheinlich ähnlich)

![Bildschirmfoto_2019-12-20_09-07-11](https://user-images.githubusercontent.com/31984939/71240130-a305d380-2308-11ea-97f2-7ffa44c0a0e3.png)

**Expected behavior**
Nummern sollten nicht überlappen. Mein Vorschlag: die ersten vier und die letzte Ziffer  wegstreichen (und gerne ein Leerzeichen zwischen die dann ersten vier und die letzten drei einfügen). Die wegfallenden Ziffern sind redundant bzw uninteressant. (9380 für alle HG-Züge vorne, Kontrollziffer hinten).

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser vivaldi (chromium)
 - Version 2.9.1705.41 (Stable channel) (64-Bit)

**Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - OS: Android 7.1.2
 - Browser opera
 - Version 55.2.2719.50740

**Additional context**
Wenn mein grep-foo in deinem Repository richtig funktioniert, müsste die Nummer in Zeile 102 in src/client/Common/Components/Reihung/Fahrzeug.tsx geschrieben werden. Ich würde gerne einen patch zu schreiben versuchen und dir einen pull-request schicken, aber ich weiß nicht, wie ich es ausprobieren könnte :)

Gerne auf twitter: [@baeuchle](https://twitter.com/baeuchle).

**Comment by marudor** [comment]
Bekannt. Da eher zu debug zwecken existent erst mal niedrige Prio.

**Comment by MarkMcWire** [comment]
Darüber hinaus fehlen bei einigen Zügen die Namen. Bei ICE0152 das "Hanau" und bei ICE0166 das "Gelnhausen". Beziehst du diese Daten direkt aus der API der Bahn oder generierst du die Namen aus einer separaten Datenquelle?
