### ISSUE TITLE
Doppelte Zugnummern

### ISSUE THREAD

**Issue by Sbahnfreund-Stuttgart** [marudor/BahnhofsAbfahrten#176]
Bei der DB scheint es doppelt vergebene Zugnummern zu geben.
Beispiel abgerufen am 20.12.2019 11:02: https://marudor.de/details/S7127:
ist einerseits eine S7 in Berlin, andererseits eine S1 in Stuttgart, Solche Fälle gibt es häufiger - oft haben Berliner S-Bahnen die gleichen Zugnummern, wie Stuttgarter.
Ist geplant bei Eingabe der Zugnummer abzufragen, welchen Zug man meint? Denn ich habe keinen Weg gefunden, die Stuttgarter S1 aufzurufen.
Danke schonmal für die tolle Website!
Aufgerufen am 20.12.2019 via PC

**Comment by gromlix** [comment]
Ich habe dasselbe mit ICs festgestellt. Den IC149 am 26.12 gibt es einmal in Dänemark  und andererseits als Verbindung Amsterdam - Berlin. Ich sitze gerade in letzterem und bekomme immer den anderen angezeigt...

Ansonsten super Webseite! :-)

**Comment by ij0n** [comment]
Kann ich so reproduzieren. Der IC 145 von Amsterdam nach Berlin Ostbahnhof wird in den Bahnhofsabfahrten angezeigt, klickt man drauf, kommt man zu einem dänischen Zug. https://marudor.de/details/IC%20145/1577786400000

**Comment by marudor** [comment]
Für Details page fixed. Für die Zugsuche noch nicht, kommt noch.
Vergleich: https://marudor.de/details/IC%20145/1577872800000?station=8011160
