### ISSUE TITLE
Reihenfolge der Zugabfahrten zu statisch

### ISSUE THREAD

**Issue by mm-chen** [marudor/BahnhofsAbfahrten#18]
**Describe the bug**
Ist ein zug verspätet, wandert dieser nicht in der Reihenfolge nach unten.

**To Reproduce**
Gehe zum Beispiel zum Bahnhof Köln Hbf.
Wenn Züge verspätet fahren, und pünktliche Züge diese überholten, dann werden die verspäteten Züge nicht hinter den pünktlichen einsortiert.

**Expected behavior**
Reihenfolge der Züge anhand der tatsächlichen Abfahrtszeit sortieren, so, dass die Reihenfolge dynamisch ist

**Screenshots**
https://malte-modler.de/index.php/s/8eNnAx3r5tLEr4w

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a2
 - OS: Android 9
 - Browser: Google Chrome 75.0.3770.101

**Comment by marudor** [comment]
Kein Bug, Absicht.

Sonst findet man keine Züge wenn diese hohe Verspätung haben und das bisher unbekannt ist. Würde einfach so aussehen als wäre der Zug nicht da. => bleibt so.
