### ISSUE TITLE
zusätzliche Datenquelle Colibri (evtl. GPS für Regio)

### ISSUE THREAD

**Issue by flesser** [marudor/BahnhofsAbfahrten#183]
Unter https://www.zugradar24.de/ gibt es eine öffentliche Karte aller Fahrzeuge, die mit Colibri (WLAN für Regio) ausgestattet sind. Hauptsächlich sind das also REs und S-Bahnen in verschiedenen Regionalnetzen, aber es scheinen auch einige ICs dabei zu sein. ([Quelle: DB Fahrzeuginstandhaltung](https://www.db-fzi.com/fahrzeuginstandhaltung-de/leistungsportfolio/produkte-und-innovationen/Colibri/colibri-3245148))

Keine Ahnung, wie live die Daten wirklich sind, wäre aber vielleicht mal einen Blick wert zur Ergänzung von [marudor.de/map](https://marudor.de/map)?

**Comment by marudor** [comment]
Hab keine Mehrdaten im vergleich zur aktuellen Karte gefunden.
Vermutlich exposen sie auch nur errechnete Positionen (Oder die Züge die das haben sind im HAFAS GPS.

**Comment by marudor** [comment]
Hab keine Mehrdaten im vergleich zur aktuellen Karte gefunden.
Vermutlich exposen sie auch nur errechnete Positionen (Oder die Züge die das haben sind im HAFAS GPS.
