### ISSUE TITLE
Favoriten für Züge

### ISSUE THREAD

**Issue by gromlix** [marudor/BahnhofsAbfahrten#187]
Ich nutze die Webseite häufiger um konkrete Züge aufzulisten, als das ich einen Abfahrtsplan aufrufe. Mir würde es daher sehr helfen, wenn ich für bestimmte Züge ein Bookmark anlegen könnte...

**Comment by marudor** [comment]
Einfach Bookmark des browsers nutzen.
z.B. https://marudor.de/details/ICE%2072
