### ISSUE TITLE
Details click leads to wrong train

### ISSUE THREAD

**Issue by GerJuli** [marudor/BahnhofsAbfahrten#190]
Details click leads to wrong train

1. Go to https://marudor.de/Stuttgart%20Hbf
2. Click on a S1 in direction Kirchheim/Teck
![Screenshot from 2019-12-28 18-27-33](https://user-images.githubusercontent.com/25753802/71547401-f4186600-299f-11ea-8b06-2f47f96e2c07.png)
3. Click Details (link https://marudor.de/details/S%207154/1577551560000?line=1)
![Screenshot from 2019-12-27 17-35-27](https://user-images.githubusercontent.com/25753802/71547416-0a262680-29a0-11ea-85e8-99f333f4cf3d.png)
4. End up on Details of S-Bahn of Berlins S7

I expected to be at details of the S1 to Kirchheim. 

Works for other S-Bahnen

Desktop
 - OS: Linux
 - Browser: Firefox

**Comment by marudor** [comment]
Fixed already. The link with ?line= is deprecated. Currently links look like this: https://marudor.de/details/S%207102/1577936760000?station=8098096

Basically this describe a S 7102 that has the following station in its route: 8098096 (EVA ID of first station of the S-Bahn)
