### ISSUE TITLE
Zugsuche hat keine Auswahl bei mehrfach vergebener Zugnummer

### ISSUE THREAD

**Issue by schleppnetztag** [marudor/BahnhofsAbfahrten#192]
**Describe the bug**
Eine im Netz der DB mehrfach vergebene Zugnummer führt dazu, dass die Zugsuche einen der Züge darstellt anstelle eine Auswahl zwischen diesen zu ermöglichen.

**To Reproduce**
1. Zugsuche anklicken
2. Eine mehrfach vergebene Zugnummer mit Zuggattung eingeben, beispielsweise S 37513 für den aktuellen Tag
3. Ein Zuglauf wird angezeigt, eine Auswahlmöglichkeit eines bestimmten Zuges fehlt.

**Expected behavior**
Es fehlt ein Auswahldialog, der zwischen den verschiedenen Zügen unterscheidet. Im Beispiel ist die S1 von Wedel(Holst) nach Hamburg-Poppenbüttel von der S5X von Halle(Saale)Hbf nach Zwickau(Sachs)Hbf nicht unterscheidbar, weil beide die Zugnummer 37513 führen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (64 bit)
 - Version 71.0

**Additional context**
Mir ist bewusst, dass auf reiseauskunft.bahn.de die Suche nach Zugnummern für S-Bahnen nicht möglich ist. Ich nehme aber an, dass jeweils beide Züge abrufbar sein müssten da einer von beiden korrekt angezeigt wird. Auf https://fahrplan.oebb.at/bin/trainsearch.exe ist das jedenfalls möglich (auch wenn das nichts mit den DB-APIs zu tun hat) wenn man die Checkbox "Nur Fahrten in Österreich" deselektiert.

**Comment by Sbahnfreund-Stuttgart** [comment]
Ist das gleiche Problem wie das hier: https://github.com/marudor/BahnhofsAbfahrten/issues/176
Und wird bald behoben

**Comment by marudor** [comment]
Korrekt.
Ich hab schon ne Idee, aber keine Zeit bisher.
Problem bekannt. Ich lass das hier mal offen zum tracken.

**Comment by Sbahnfreund-Stuttgart** [comment]
Das Problem lässt sich, wie ich festgestellt habe, umgehen, wenn man an die Zugnummer ein "?station=" mit der IBNR des nächsten Bahnhofs dranhängt. Funktioniert zumindest bei mir super...

**Comment by marudor** [comment]
Korrekt - das benutz ich um die links korrekt zu mappen.
Das favorisiert die Züge welche an der angegeben station halten.
Gedacht ist es dort den Startbahnhof anzugeben.

**Comment by schleppnetztag** [comment]
Der Workaround ist ja einfacher als gedacht, danke. Aus Faulheit habe ich direkt in die Zugsuche "S 37513?station=8010159" eingegeben, das funktioniert auch. Allerdings sieht die URL dann so aus https://marudor.de/details/S%2037513?station=8010159/1578546302593 - es ist also unerheblich ob ich den Parameter am Ende der URL ran hänge oder direkt in die Zugsuche eingebe?

**Comment by marudor** [comment]
Ne - dann wars zufall. Funktioniert nur wenns am Ende ist.
