### ISSUE TITLE
Unterstützung des RMV (Rhein-Main-Verkehrsverbund

### ISSUE THREAD

**Issue by AnsgarH1** [marudor/BahnhofsAbfahrten#193]
Es wäre toll wenn die RMV (Rhein-Main-Verkehrsbund) API bei der Provider Auswahl mit eingebunden werden könnte, soweit ich weiß läuft diese auch über HAFAS. 

Hier der link zur Seite vom RMV: https://opendata.rmv.de/site/start.html

**Comment by marudor** [comment]
Wenn du oder jemand anders das mgate von denen findet gerne. Sonst nicht.

**Comment by derhuerst** [comment]
related: https://github.com/schildbach/public-transport-enabler/issues/118, https://github.com/schildbach/public-transport-enabler/issues/240

**Comment by marudor** [comment]
Supported for a whuile now.
