### ISSUE TITLE
Redesign (aus staticTzInfo.json) wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by flesser** [marudor/BahnhofsAbfahrten#194]
**Describe the bug**
Tz4651 ist definitiv redesignt, wird aber in den Abfahrten nur als ICE 3 (BR406 DE) angezeigt.

Die Redesign-Info scheint hier zwar vorhanden zu sein, wird nur offenbar nicht im Frontend angezeigt: https://github.com/marudor/BahnhofsAbfahrten/blob/88d6ee845e3c04cc249aa1874ccfc12712fdb64a/src/server/Reihung/staticTzInfo.json#L3540-L3542

**To Reproduce**
In einem Umlaufplan nachsehen, auf welchem Zug Tz4651 fährt und den auf marudor.de raussuchen (aktuell: ICE 11).

**Expected behavior**
Tz4651 sollte mit dem Warnhinweis "Redesign" versehen werden.

**Screenshots**
![image](https://user-images.githubusercontent.com/510681/71802863-6acbf800-305f-11ea-9add-ce67bb03fb6d.png)

**Additional context**
Strenggenommen ist Tz4651 auch kein "ICE3 DE", sondern gehört wie auch Tz4652 und Tz4653 den Holländern: https://nl.wikipedia.org/wiki/Baureihe_406#NS

**Comment by marudor** [comment]
Das DE kommt daher das es Deutsche UIC Nummern sind. Daher belasse ich es auch dabei.
Rest: Schau ich mir an.

**Comment by flesser** [comment]
Bin auf einen neuen Fall gestoßen:
TZ0321 wird als Redesign angezeigt:
![image](https://user-images.githubusercontent.com/510681/75223019-d4d26500-57a5-11ea-8954-9a6a8afd0f2c.png)
Laut https://github.com/marudor/BahnhofsAbfahrten/blob/master/src/server/Reihung/staticTzInfo.json#L1930-L1950 (und meinem Rücken) ist es aber noch ein "guter alter".

(Außerdem: hat es einen Grund, dass in der staticTzInfo.json für diesen und weitere Züge die UIC-Nummern aller Wagen doppelt angegeben sind?)

**Comment by marudor** [comment]
Das Redesign kommt da dort ein WRmz drin ist. Eig. passiert das nur bei Redesign.
Ich bau mal ein das die Liste doch vorrang hat.

Und ja: Das kommt vom WIFI Monitoring. Pre Redesign Züge habe 2 APs pro Wagen => UIC Nummern doppelt.

**Comment by biolauri** [comment]
_Off-topic:_ Zum WIFI-Monitoring habe ich eine Frage: Gibt es das noch? Habe das bereits seit einiger Zeit nicht mehr gesehen und fand das ziemlich hilfreich. Oder bin ich zu blind, das zu sehen?

**Comment by marudor** [comment]
Nein. Ich hab da sicherheitsrelevante Dinge gefunden und es gemeldet. Reaktion: Down genommen.

**Comment by biolauri** [comment]
Vielen Dank für die Info! Schade, aber find ich prinzipiell gut so. 👍  
Ich hoffe, dass die Schnittstelle wieder live geht, wenn die sicherheitsrelevanten Dinge raus sind.
