### ISSUE TITLE
Wagentypen für MET falsch

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#198]
**Describe the bug**
Die 2. Klasse-Wagen bei Zügen auf denen der MET fährt werden als Bpmz angezeigt (wahrscheinlich ohne Validierung aus der API übernommen) und auch diese Sitzpläne verlinkt. Diese sind aber falsch, da die Wagentypen Apmz sind (steht richtig im verlinkten WRSheet)

**To Reproduce**

Zugnummer aufrufen die mit einer MET-Leistung gefahren wird (Aktuell ICE 1040, 1043, 1191, 1196) und Wagenreihung anzeigen.

**Expected behavior**

Wagentypen in WRSheet und Anzeige sind gleich. 
Beim Parsen erkennen ob MET (durch Wagenzusammenstellung und Lok/Wagennummern einfach zu erkennen) und dann Wagentypen anpassen. 

**Screenshots**
<img width="1241" alt="Bildschirmfoto 2020-01-07 um 10 21 49" src="https://user-images.githubusercontent.com/11199213/71965609-4ce9c900-3200-11ea-9923-56f4282f8c74.png">

**Additional context**

**Comment by marudor** [comment]
Sind es immer Apmz? Also gibt es keine Bpmz sonder nur Apmz?
Afaik gibts ja 2 Arten von 2. Klasse im MET? (Bisher einmal gefahren und da erste)

**Comment by f2k1de** [comment]
Heute noch mal den Zug angeschaut. 
Die beiden Wagen der Kategorie Traveller mit 2x2 Bestuhlung sind als Apmz beschriftet. 
(Hat vermutlich historische Gründe, da diese bis 2001 als Silence unterwegs waren und erst danach als 2. Klasse Äquivalent mit der Traveller Kategorie gedacht waren)
