### ISSUE TITLE
BahnComfort Plätze für MET-Leistungen anzeigen

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#199]
**Describe the solution you'd like**
Anzeige der BahnComfort Plätze bei Zügen die mit MET Material gefahren werden. 

* 2 . Klasse: Wagen 5 91-106
* 1 . Klasse: Wagen 6 61-66

**Comment by marudor** [comment]
Sind sogar schon hinterlegt. Allerdings erwarte ich das es in der WR mitkommt ob es welche gibt...
Vmtl fehlt das. Investigating.
