### ISSUE TITLE
Search for train numbers

### ISSUE THREAD

**Issue by simonszu** [marudor/BahnhofsAbfahrten#20]
**Is your feature request related to a problem? Please describe.**
Sometimes i am sitting in a train, and the Zugchef announces an undefined problem. The Navigator tells me an estimated delay, but since you provide much more real time information, i'd like to search for a train number if there is a more precise delay announced, or a more precise problem description.

**Describe the solution you'd like**
A input box to search for a specific train, so that i see its current status at a glance. 

**Describe alternatives you've considered**
Currently i am searching for the next station en route, and scroll manually to find the specific train. This is sometimes confusing since i do not realize if the list is sorted by scheduled or actual departure time, but that's another issue, i think.

**Comment by marudor** [comment]
Always sorted by scheduled departure time. If no departure exists arrival time is used to sort. 
There is "zugsuche" now. It redirects to detail page for that train. Will be using iris data soon. (currently HAFAS only)
So already existing

**Comment by marudor** [comment]
If you use "Zugsuche" the current station will have IRIS Information. I will also show IRIS Messages.
UI is most likely optimizeable. But feature wise I've got what you want.

**Comment by simonszu** [comment]
Thanks. The UI is functional, and i get the information i need.
