### ISSUE TITLE
Es werden teils ausländische Zugläufe angezeigt, auch wenn es einen der DB gibt

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#212]
**Describe the bug**
Es werden bei manchen Zugnummern die auch in Nachbarländern, zu denen es ebenfalls Daten gibt unter Zugsuche angezeigt, obwohl es auch Daten für einen Zug der DB gibt (die in den meisten Fällen die gesuchten Daten sind)

**To Reproduce**
1. Zugsuche -> z.B. IC 2170
Es wird ein InterCity von Den Haag Centraal nach Amsterdam angezeigt.
Es gibt aber auch einen InterCity mit der Nummer 2170 von Berlin Hbf(tief) nach Rostock Hbf am gleichen Tag.

**Expected behavior**
Auswahl, welcher Zug denn jetzt der gewünschte ist. 

**Screenshots**
![Screenshot from 2020-01-13 12-46-16](https://user-images.githubusercontent.com/11199213/72253830-bacc3100-3602-11ea-86e7-cbe927f02d04.png)
![Screenshot from 2020-01-13 12-46-09](https://user-images.githubusercontent.com/11199213/72253831-bacc3100-3602-11ea-92ea-5a1dba9092cb.png)

**Comment by marudor** [comment]
Duplicate #192
