### ISSUE TITLE
Berlin Hauptbahnhof wird zu Berlin Ostbahnhof

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#214]
**Describe the bug**
Auf der Favoritenseite wird beim Antippen von Berlin Hauptbahnhof die Abfahrten von Berlin Ostbahnhof aufgerufen.

**To Reproduce**
marudor.de öffnen -> Berlin Hauptbahnhof antippen

**Expected behavior**
Berlin Hauptbahnhof wird auch angezeigt

**Screenshots**
![ezgif-3-2885f215dd81](https://user-images.githubusercontent.com/11199213/72332203-e827e600-36b9-11ea-82e1-251eeef59533.gif)

**Comment by marudor** [comment]
Uff. Danke Bahnapis oder so...
Fix ich direkt mal.
