### ISSUE TITLE
Ursprüngliche Abfahrzeit sollte auch angezeigt werden 

### ISSUE THREAD

**Issue by Grauen** [marudor/BahnhofsAbfahrten#222]
Wenn man Marudor für einen kleinen Bahnhof verwendet, kommt man gut klar. Vielen Dank! 

Für große Bahnhöfe kann man aber noch ein wenig gutes für Pendler tun. Denn hier ist die Zug liste oft so groß und voller Verspätungen, dass man den Überblick verliert. 

Als Pendler kennst du deinen Zugtyp und wann der Zug los fahren soll. Wenn da jetzt 30 ics sind, bei denen nur die Abfahrtszeit inklusive Verspätung steht, muss man die Liste durchsuchen. Nach einer bekannten Uhrzeit zu suchen ist viel schneller.

Wäre cool, wenn man das noch zusätzlich in den settings anbieten kann.

**Comment by marudor** [comment]
Settings - Neue Ankunft bei Verspätung ausmachen.

**Comment by LaurenzRe** [comment]
@Grauen Hi, mir ist leider nicht bekannt wie man dich direkt anschreiben kann. Deswegen hier.
Ich habe deinen Username auf der Barbot Bender Website (https://barbot-bender.jimdofree.com/) gefunden, dort hast du vor ein paar Jahren nach einem Quellcode gefragt, nun meine Frage:
Hast du den Quellcode jemals erhalten und vielleicht sogar noch irgendwo. Ich bin dabei das Projekt nachzubauen, aber das Programm braucht kleine Anpassungen. Ich hoffe du kannst mir helfen.
Erreichbar bin ich unter dieser Email: Laurenz24@gmx.de
Danke für deine Hilfe
