### ISSUE TITLE
Delete selected Station

### ISSUE THREAD

**Issue by raspyweather** [marudor/BahnhofsAbfahrten#23]
**Describe the bug**
After selecting a Station, backspace does not work, nor is it possible to change the selected Station after one has been selected.

**To Reproduce**
1. Go to https://marudor.de/routing/0103484/0103485
2. Click on the first or second text input
3. Try to delete its input
4. See no change

1. Go to https://marudor.de/Hannover%20Hbf
2. Click in the text input
3. Try to change the selected station
4. See no change

**Expected behavior**
Changing a selected station is possible, using backspace to delete a character is possible.

**Desktop:**
 - Browser Chrome, Firefox

**Smartphone:**
 - PWA on Android 7.1
-  Device: AGM X2

**Comment by marudor** [comment]
Changing works for me. Yes you can't delete the current input. But if you just type something it works. (Bad UX)
