### ISSUE TITLE
Daten für NL für /map

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#239]
**Describe the solution you'd like**
Anzeige weiterer Länder (und nicht nur begrenzt auf DE/AT) auf /map

**Additional context**
API für Niederlande findet sich hier: https://vt-acc.ns-mlab.nl/v1/location/treinen

**Comment by marudor** [comment]
Momentan ist /map nur side side project. (Darum auch nirgends verlinkt)
Ergibt sich aus HAFAS.
Polen z.B. kam letzte Woche dazu durchs finden vom passenden HAFAS.

Momentan keine Kapazität das hinzu zu fügen.

**Comment by marudor** [comment]
/map ist erst mal tot. Folglich irrelevant.
