### ISSUE TITLE
Favoriten für Routing

### ISSUE THREAD

**Issue by meyju** [marudor/BahnhofsAbfahrten#245]
Als Pendler finde ich die genauen Informationen (Abfahrzeiten und Zugreihenfolge) sehr gut. Allerdings interessieren mich nicht abfahren von einem einzelnen Bahnhof (was z.B. in München Hbf sehr viele sind), sondern immer wieder die selben Verbindungs-Strecken. 

Interessant wäre eine Favoriten Funktion im Routing Bereich mit Start- und Zielbahnhof. Hier aber auch mehrere (Zur Arbeit und wieder zurück).

**Comment by marudor** [comment]
Mit Uhrzeit? Also willst du nen shortcut für A -> B um 12:30 und Datum ist dann ebe ndas an dem du klickst.
Oder reicht A->B jetzt?

**Comment by meyju** [comment]
Ich denke "A->B ab jetzt" sollte passen. Da es typisch eine Aktion ist, wenn man auf dem Weg zum Bahnhof ist.
