### ISSUE TITLE
Datumseingabe bei den Abfahrten oder 'Später'-Schaltfläche

### ISSUE THREAD

**Issue by RobindotK** [marudor/BahnhofsAbfahrten#25]
Ich würde mir wünschen dass ich bei den Abfahrten auch die Möglichkeit habe 'Später' anzuklicken (um über die max. 300 Min lookahead zu kommen) oder auf den nächsten Tag klicken kann - hier auf dem Lande fährt abends ja nix mehr ;-)

**Comment by marudor** [comment]
Problem dabei: Die Daten sind nunmal echtzeit. Ich hab nur so +-8 Stunden. Regionalverkehr weniger an Daten. Die 300 Minuten sind oft schon ungenau. Dann lieber mit routing schauen und wenige Stunden vor Abfahrt dann mit der Abfahrtstafel.
