### ISSUE TITLE
Bahnhof Hamm(Westf) now Hamm(Westf) Hbf

### ISSUE THREAD

**Issue by sunflower-seed** [marudor/BahnhofsAbfahrten#251]
**Describe the bug**
A quicksearch proposal for search "Hamm" returns Hamm(Westf), but Hamm(Westf) is since December 2019 Hamm(Westf) Hauptbahnhof.

The details view show the current, valid station name.

**To Reproduce**
1. Go to Startpage
2. Click on Search field
3. Enter "Hamm"
4. See proposed results, with error

**Expected behavior**
Show new, correct station name

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser FF
 - Version current

**Comment by marudor** [comment]
Closed - I use DB APIs - they haven't changed it. I won't start to manually change names.
