### ISSUE TITLE
500 internal server error 

### ISSUE THREAD

**Issue by Dungu-byte** [marudor/BahnhofsAbfahrten#265]
**Describe the bug**
I'm fairly new to this topic so please have mercy with me. 

When I try to post to the tripsearch API I get 500 internal Server error as a response. 

I'm using node.js v8.16.2 to execute the following Script: 
`const fetch = require('node-fetch');
const url = 'https://marudor.de/api/hafas/v1/tripSearch'

let request = async () => {
  let response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      "start": "Hamburg Hbf",
      "destination": "Berlin Hbf",
    })
  });
  console.log(response);
}

request();
`

I can't retrace what could be the issue. I as well tried a more extensive post-request which included all the fields from the documentation page. 

Can someone help me out on this one? Or perhaps can show me a working example since this could very likely solve my problems.

**Comment by marudor** [comment]
Start/destination have to be EVA Numbers - not names.

**Comment by Dungu-byte** [comment]
I read the whole documentation and tried the EVA number. Still I get the error, I couldn't really analyse my fault with the docs. Could you perhaps post an example? 

Many sorry for bothering you with these questions.

**Comment by marudor** [comment]
Easy example is if you just sniff what marudor.de does on routing.
API is not focus => no further documentation (I do not have enough time to fully support it)
But looking into a request should give you enough hints.
