### ISSUE TITLE
Feature Request: Bessere Wagenreihung für neue KISS-Intercity

### ISSUE THREAD

**Issue by flesser** [marudor/BahnhofsAbfahrten#270]
Seit gestern fahren ja die "neuen" gebrauchten Westbahn-KISS-Züge als Intercity Berlin-Rostock [[1]](https://bahnblogstelle.net/2020/03/07/neue-doppelstock-intercity-nehmen-betrieb-auf-zugtaufen-in-rostock-und-dresden/).

In deiner Wagenreihung sieht das zur Zeit so aus (Beispiel IC 2274):
![image](https://user-images.githubusercontent.com/510681/76192031-153bd500-61e1-11ea-86fe-2874393276da.png)
* Fahrzeug wird als "IC (CH)" angezeigt --> könnte verbessert werden.
* Triebzugnummer aus der API(?) ist ICK4114 (vmtl. DB-Code für Intercity Kiss?)

Im oben verlinkten Artikel ist außerdem zu lesen, dass einzelne Züge auf Namen getauft wurden. Laut Foto z.B. der 4117 auf „Mecklenburgische Ostseeküste“.
Würde ein einfaches Hinzufügen dieser Nummern/Namen zur Liste [ICENaming.ts](https://github.com/marudor/BahnhofsAbfahrten/blob/master/src/server/Reihung/ICENaming.ts) reichen, um das auf marudor.de entsprechend anzuzeigen, oder ist da mehr Logik notwendig, weil du z.B. ICs und ICEs unterschiedlich verarbeitest?

**Comment by marudor** [comment]
Müsste reingucken ob das IC (CH) an der UIC Nummer oder an was anderem liegt.
Jap, Die API sagt ist ein ICK4114 - das kann ich nicht beinflussen.
Es könnte reichen, nicht sicher - bisher sind nur ICEs benannt.

**Comment by flesser** [comment]
> Es könnte reichen, nicht sicher - bisher sind nur ICEs benannt.

Na, dann versuch ich's doch einfach mal --> #272
