### ISSUE TITLE
Browser-timezone and real timezones can lead to probles

### ISSUE THREAD

**Issue by CryptKid** [marudor/BahnhofsAbfahrten#284]
**Describe the bug**
If a browser uses UTC (many configs of firefox do, for privacy reasons) all times are offset by an hour (that's probably a feature although i find it irritating sometimes), but when a train in Britain is involved (i.e. Eurostar) it already uses UTC and still gets subtracted by 1 hour.

**To Reproduce**
Use a browser with UTC as timezone (i.E. firefox with "Advanced Tracking Protection set to "strict") and search the departure time of a Eurostar in Britain

**Expected behavior**
Either always use local time of the stop or at least check the calculation of browser local time fits the timezone, your data is in

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Mozilla Firefox
 - Version 73.0.1

**Comment by marudor** [comment]
Not a bug.
I will use the timezone of your browser. If thats UTC it's your responsibility.
For the Eurostar the problem lies within the API and might be a bug.
