### ISSUE TITLE
Certain Most Used Stations don't work

### ISSUE THREAD

**Issue by raspyweather** [marudor/BahnhofsAbfahrten#288]
**Describe the bug**
Most used stations should exist.

**To Reproduce**
1. Go https://marudor.de
2. Click on one of these:
- 'Frankfurt (Main) Hbf'
- 'Karlsruhe Hbf'
- 'Mannheim Hbf'
- 'Berlin Hbf'
- 'Düsseldorf Hbf'
- 'Köln Hbf'
- 'Leipzig Hbf'
4. See error "unknown error"

**Expected behavior**
Selected Station to be shown. Weirdly some like 'Hamburg Hbf' do work. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FF
 - Version 74.0

**Comment by marudor** [comment]
API Problems, not a bug.
