### ISSUE TITLE
Hauptbahnhof Südseite, Frankfurt a.M. can not be shown

### ISSUE THREAD

**Issue by Claudweb** [marudor/BahnhofsAbfahrten#29]
**Describe the bug**
When searching for "Hauptbahnhof Südseite, Frankfurt a.M." the results for "Frankfurt-Nied" are shown, which is a completely different station.

**To Reproduce**
1. Go to 'https://marudor.de/Hauptbahnhof%20S%C3%BCdseite%2C%20Frankfurt%20a.M.'
4. Results shown are from Frankfurt-Nied

**Expected behavior**
Show results for Hauptbahnhof Südseite, Frankfurt a.M.

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser [e.g. chrome, safari]: Tried latest chrome and firefox

**Smartphone (please complete the following information):**
Also reproduces on Android Chrome

**Comment by marudor** [comment]
Frankfurt südseite has no real train departures. => You won't find any departures for it. => Station is unknown for departures.
