### ISSUE TITLE
Missmatch between train types.

### ISSUE THREAD

**Issue by MIntrovrt** [marudor/BahnhofsAbfahrten#297]
**Describe the bug**
connection with ICE613 shows (4) as ICE type in routing view and detail view header, but shows ICE 3 Series 1 in detail view

similar to #241

**To Reproduce**
1. Go to Routing (I used this query https://marudor.de/routing/008000041/008000107/1586788200000/)
2. Click on 'Search'
3. Click on the Connection
4. See first train type.
5. Click details (https://marudor.de/details/ICE 613/1586788860000)
4. See different train type

**Expected behavior**
Train type displayed in the routing view matches train type in detail view

**Screenshots**
https://i.imgur.com/KVEayaR.png

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 
 - Version: 75.0

**Comment by marudor** [comment]
Not a bug, in brackets is planned type, not real type.
