### ISSUE TITLE
noHeader parameter ignored

### ISSUE THREAD

**Issue by heinemml** [marudor/BahnhofsAbfahrten#30]
**Describe the bug**
The Header-Searchbar is shown even when `noHeader=true` is passed as get Parameter.

**To Reproduce**

https://marudor.de/N%C3%BCrnberg?lookahead=120&lookbehind=5&onlyDepartures=true&autoUpdate=60&theme=dark&noHeader=true

**Expected behavior**
Header Bar is not shown

**Comment by heinemml** [comment]
There seems to be a general problem with the query parameters. `autoUpdate` is also not applied. Was there an API change?

**Comment by marudor** [comment]
I Accidently removed that feature. Will be back soon.

**Comment by marudor** [comment]
Fixed. onlyDepartures has it's own ticket #31
