### ISSUE TITLE
Marudor API trainSearch responding 500

### ISSUE THREAD

**Issue by NiklasDah** [marudor/BahnhofsAbfahrten#304]
**Describe the bug**
Hafas1 API Trainsearch funktioniert nicht wie erwartet https://docs.marudor.de/#operation/TrainSearch 

**To Reproduce**
`GET https://marudor.de/api/hafas/v1/trainSearch/ICE72`
Outputs:
`{"expose":false,"statusCode":500,"status":500}`

**Expected behavior**
Antwort mit Zugdaten

**Desktop (please complete the following information):**
 - Windows, Linux
- Firefox, curl, Chrome

**Additional context**
-

P.s.: Sorry für Edit, Githubs Strg+Enter war schneller als ich.

**Comment by marudor** [comment]
Fixed im nächsten release.
Ist allerdings deprecated - /journeyMatch ist besser.
