### ISSUE TITLE
Fahrzeug Reihung

### ISSUE THREAD

**Issue by kevin270602** [marudor/BahnhofsAbfahrten#313]
Hallo liebes marudor Thema, es wäre schön wenn bei allen Regionalzüge und S-Bahn die Fahrzeuge drin stehen würde
Mit freundlichen Grüßen
K.Beck

**Comment by marudor** [comment]
Sofern verfügbar sind sie da. Der Rest liegt an fehlenden Daten seitens der Bahn.
=> Nicht fixbar.

**Comment by kevin270602** [comment]
Ich könnte manche Fahrzeug Reihungen auch eintragen wenn das möglich wäre?

marudor <notifications@github.com> schrieb am Fr., 24. Apr. 2020, 19:07:
