### ISSUE TITLE
searchOnTrip wird bei manchen ctxRecon nicht angesprochen

### ISSUE THREAD

**Issue by TheZenti** [marudor/BahnhofsAbfahrten#32]
**Beschreibung des Bugs**
Bei bestimmten `ctxRecon` verwendet koa-router nicht die vorgesehene Route für searchOnTrip, sondern wirft stattdessen 404.

**Reproduzierung**
`curl https://marudor.de/api/hafas/current/searchOnTrip/¶HKI¶T$A=1@O=München%20Hbf@L=8000261@a=128@$A=1@O=Köln%20Messe/Deutz%20Gl.11-12@L=8073368@a=128@$201908281055$201908281514$ICE%20%20720$$1$§W$A=1@O=Köln%20Messe/Deutz%20Gl.11-12@L=8073368@a=128@$A=1@O=Köln%20Messe/Deutz%20Gl.%209-10@L=8083368@a=128@$201908281514$201908281521$$$1$§T$A=1@O=Köln%20Messe/Deutz%20Gl.%209-10@L=8083368@a=128@$A=1@O=Köln%20Hbf@L=8000207@a=128@$201908281521$201908281523$S%20%20%20%20%20%206$$1$`

**Erwartetes Verhalten**
Ausgabe von JSON, für obige Anfrage: https://gist.github.com/TheZenti/338acd238a571f44754ac859c2377d18

**Beobachtetes Verhalten**
HTTP 404, ohne dass der Request bei der vorgesehenen Route landet.

**Mögliche Lösung**
searchOnTrip funktioniert, wenn die Route von GET in POST umgewandelt wird, und `ctxRecon` als POST-Datum übergeben wird. Beispiel-curl:
`curl 'http://<SERVER>/api/hafas/current/searchOnTrip' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*'  --data-binary '{"ctxRecon":"¶HKI¶T$A=1@O=München Hbf@L=8000261@a=128@$A=1@O=Köln Messe/Deutz Gl.11-12@L=8073368@a=128@$201908281055$201908281514$ICE  720$$1$§W$A=1@O=Köln Messe/Deutz Gl.11-12@L=8073368@a=128@$A=1@O=Köln Messe/Deutz Gl. 9-10@L=8083368@a=128@$201908281514$201908281521$$$1$§T$A=1@O=Köln Messe/Deutz Gl. 9-10@L=8083368@a=128@$A=1@O=Köln Hbf@L=8000207@a=128@$201908281521$201908281523$S      6$$1$"}' --compressed`

**Comment by marudor** [comment]
It's a post for a while now.
