### ISSUE TITLE
UI improvement: separate trains visually in routing

### ISSUE THREAD

**Issue by TechMoritz** [marudor/BahnhofsAbfahrten#330]
**Is your feature request related to a problem? Please describe.**
Currently the train routing view is a little bit "confusing" because there is no clear separation between trains.

**Describe the solution you'd like**
My suggestion would be:
![image](https://user-images.githubusercontent.com/23395732/81218484-8b409a80-8fde-11ea-8a36-702c879d44b8.png)

**Comment by marudor** [comment]
-
