### ISSUE TITLE
Negative Umstiegszeiten im Routing

### ISSUE THREAD

**Issue by TechMoritz** [marudor/BahnhofsAbfahrten#331]
**Is your feature request related to a problem? Please describe.**
Es kommt häufiger vor, dass man beispielsweise Umstiegszeiten von -1 Minute hat, um einen Anschlusszug zu bekommen. In der Reiseauskunft wird das nicht angezeigt, da der Zug theoretisch nicht erreichbar ist. Praktisch ist das aber häufig der Fall, da die Ankunft entweder erfrüht erfolgt oder die Abfahrt des zweiten Anschlusszugs sich verspätet (aber noch nicht direkt im HAFAS eingetragen wird).

**Describe the solution you'd like**
Auch negative Mindestumstiegszeiten ermöglichen. Wenn die API das nicht direkt unterstützt, evtl. bei Zwischenhalten eine zweite Abfrage mit früherer Abfahrtszeit durchführen.

**Comment by marudor** [comment]
Werd nicht anfangen das HAFAS zu zerstückeln. Das eh schon frickelkram. Das Routing von denen ist halt meh - kann ich leider nix ändern.
Dazu ist das persönliche präferenz. Menschen möchten das oft auch genau nicht. Wenn du wirklich selbst umstiege planen willst (Worauf das ja hinaus läuft) musst du bei verspätung vor allem einfach die Abfahrtstafel nutzen.

**Comment by DerChaot** [comment]
Vielleicht ist das was für dich Moritz? https://github.com/traines-source/time-space-train-planner
Eine Webseite gibt es dafür leider noch nicht.

**Comment by MoritzWeber0** [comment]
Amazing, thank you @DerChaot!
