### ISSUE TITLE
Bahnhofspläne für Stationen in Schleswig-Holstein/Hamburg

### ISSUE THREAD

**Issue by n1kPLV** [marudor/BahnhofsAbfahrten#343]
**Is your feature request related to a problem? Please describe.**
Wie in #320 bereits beschrieben gibt es Bahnhofspläne nur für die größeren Bahnhöfe. Für andere Haltestellen funktioniert die Schaltfläche nicht. 

**Describe the solution you'd like**
Die Nah.SH und der HVV stellen eigene Stationspläne bereit. Zumindest für Stationen in Schleswig-Holstein außerhalb des HVV sind diese relativ einfach abzurufen. Für die Reiseplanung wäre es sinnvoll diese einzubinden.

**Additional context**
Für Stationen in Schleswig-Holstein außerhalb des HVV liefert der HVV den Stationsplan unter der URL "https://geofox.hvv.de/images/mobi/pdf/<Bahnhofsname\>.pdf", wobei <Bahnhofsname\> der Name des Bahnhofes mit Unterstrichen statt Leerzeichen und Umlauten in Ersatzschreibweise ist. 

Den Plan für "Neumünster Süd" findet man beispielsweise unter "https://geofox.hvv.de/images/mobi/pdf/Neumuenster_Sued.pdf". Groß- bzw. Kleinschreibung scheint nicht relevant zu sein.

Für alle anderen Stationen gibt es sowohl vom HVV als auch von Nah.SH unterschiedliche Stationspläne, die aber keine so simple URL für den Zugriff haben. Da scheint irgendeine interne ID oder eine Art hash in die URL reincodiert zu sein. Man bekommt diese URLs über das Geofox- (HVV) bzw. HAFAS- (Nah.SH) Webinterface. Vielleicht findet ja jemand die Logik dahinter oder schafft es diese Info aus den APIs herausbekommt. Hier einmal am Beispiel von "Bad Segeberg"

Beim HVV findet man die Pläne [hier](https://geofox.hvv.de/jsf/mobiInformation.seam) und die entstehenden Links sehen so aus: "https://geofox.hvv.de/images/mobi/pdf/Bad_Segeberg_R_020818.pdf"

Der Nah.SH liefert die Stationspläne bei der [Verbindungssuche](https://nah.sh.hafas.de) aus. Die Links dieser Pläne sehen dann so aus: "https://www.nah.sh/assets/downloads/Stationsplaene/fe365a61c9/Bad_Segeberg.pdf"

**Comment by n1kPLV** [comment]
Bei der NAH.SH findet man die Pläne übrigens auch unter [https://www.nah.sh/de/karten/stationsplaene/](https://www.nah.sh/de/karten/stationsplaene/). Dort kann man zumindest Bahnhofsname und Plan URL mit Grep extrahieren. Ich hab da mal eine CSV angehängt:
[Bahnhofspläne_SH.csv.txt](https://github.com/marudor/BahnhofsAbfahrten/files/4933787/Bahnhofsplane_SH.csv.txt)

Das Extrahieren hab ich mit diesem formschönen Command gemacht:
``` bash
paste -d\; \
<(echo 'name' && (curl -s https://www.nah.sh/de/karten/stationsplaene/ |
grep -Po '<h4 class="card__list__title">\K(.+?)(?=</h4>)')) \
<(echo 'URL' && (curl -s https://www.nah.sh/de/karten/stationsplaene/ |
grep -Po '<a href\=\"\K(.+?)(?=\" target=\"_blank\" class=\"card__link\">)'|
awk "{print \"$HOSTNAME\" \$0}" -)) > Bahnhofspläne_SH.csv.txt
```

**Comment by marudor** [comment]
Die nahsh links sind alle 404 aktuell (Auch wenn ich direkt bei denen nochmal suche)

**Comment by marudor** [comment]
Aber - ich hab nen Weg gefunden für die Nah.SH dinge - und für den HVV auch.
HVV sogar direkt über evaId statt Namen, Nah.SH indirekt über evaId (damit wengier fehleranfällig)
