### ISSUE TITLE
Norddeich Mole: Züge doppelt vorhanden

### ISSUE THREAD

**Issue by NiklasDah** [marudor/BahnhofsAbfahrten#352]
**Describe the bug**
Züge in Norddeich Mole werden doppelt angezeigt

**To Reproduce**
1. goto https://marudor.de/Norddeich%20Mole
2. Züge werden doppelt angezeigt; anscheinend von Norddeich+Norddeich Mole

**Expected behavior**
Züge werden einmal angezeigt

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS, Windows
 - Browser Safari, Chrome, Firefox
 - Version Newest stable releases

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: 13.5, 10.15, 2004
 - Browser safari
 - Version N/A

**Additional context**
N/A

**Comment by marudor** [comment]
Jemand bei der Bahn kam auf die Glorreiche Idee zu sagen das Norddeich und Norddeich Mole "Meta" zueinander sind. => Das sie als eins gelten sollen.
Das wird normalerweise für sowas wie Berlin Hbf und Berlin Hbf (Tief) gemacht.
Oder Frankfurt Hbf und Frankfurt Hbf (Tief)
Da wo es für den Kunden ein Bahnhof ist aber Betrieblich mehrere. Hier ist das natürlich banane...
Bau ich nachher ne exception ein. Danke dir.
