### ISSUE TITLE
Anzeige des ICE 1 LDV

### ISSUE THREAD

**Issue by f2k1de** [marudor/BahnhofsAbfahrten#362]
**Is your feature request related to a problem? Please describe.**
Tz 155 Rosenheim ist einem eher umfangreicherem Redesign des Programmes ICE1 "LDV" (Lebensdauerverlängerung) unterlaufen und somit als erster ICE 1 dieser Art mit 9 Statt 12 Wagen unterwegs. Dieser fährt aktuell als 923/924.
Dies ist jedoch nur beim Nachzählen der Wagen in der Reihungsansicht ersichtlich, jedoch nicht aus dem Text der Bauserie darunter. 
Vgl: 
Alter ICE 1 mit 12 Wagen
![Screenshot from 2020-06-29 16-24-25](https://user-images.githubusercontent.com/11199213/86018492-bc10df00-ba25-11ea-8b69-fb56f2762b1f.png)
Neuer ICE 1 LDV mit 9 Wagen
![Screenshot from 2020-06-29 16-24-36](https://user-images.githubusercontent.com/11199213/86018546-ce8b1880-ba25-11ea-9c0b-2346d7a8951a.png)

**Describe the solution you'd like**
![Screenshot from 2020-06-29 16-27-10](https://user-images.githubusercontent.com/11199213/86018704-02663e00-ba26-11ea-8949-91b4442f7279.png)

**Comment by marudor** [comment]
Werd ich wohl ähnlich wie aktuelle Baureihen auch als manuelle Liste führen müssen. (UIC Nummer basierend)
