### ISSUE TITLE
Art des Zuges beim Nah.SH

### ISSUE THREAD

**Issue by torbenkeller** [marudor/BahnhofsAbfahrten#370]
**Problem**
Die neuen grünen Züge, die auf den Verbindungen RE7 und RE70 von Kiel nach Hamburg und zurück eingesetzt werden, haben Steckdosen, die alten roten aber nicht. Vorher weiß man leider nie, ob man nun mit einem Zug fährt der Steckdosen hat oder nicht. Es ist zwar nicht dramatisch in einem Zug ohne Steckdosen zu fahren, wenn man mit vollem Akku einsteigt, weil die Fahrt relativ kurz ist. Trotzdem wäre es vorher schön zu wissen.

**Lösung**
Das sollte in der Detailansicht mit angezeigt werden.

**Comment by marudor** [comment]
Nicht möglich, Gibt keine Daten von NAH.SH / Bahn dazu. (Wenn doch werd ich da ergänzen)
