### ISSUE TITLE
Useability Problem of "Plätze" pop up

### ISSUE THREAD

**Issue by yonie1** [marudor/BahnhofsAbfahrten#376]
If you use the "Plätze" function (click on the blue "Plätze" text in the "Wagenreihung") on desktop or mobile (Linux Chrome / Android 10 Chrome), the only way I was only able to close the popup was by pressing esc or pressing on the popup itself. I would suggest closing it if you tap anywhere else on the screen or adding a close button to it. The current way to close it is (in my opininon) counterintuitive, because the last thing the average user clicks to close a window is on the window itself.

**Comment by marudor** [comment]
Already fixed, not yet deployed.
