### ISSUE TITLE
Matches wrong station (Businesshub)

### ISSUE THREAD

**Issue by ip138** [marudor/BahnhofsAbfahrten#386]
**Describe the bug**
When calling https://marudor.de/Schorndorf, the data of "Dortmund Hbf" are being displayed. DS100 notation (https://marudor.de/TSF) matches to Schorndorf correctly (station nr. 8005424). Station API is Businesshub.

**To Reproduce**
1. (choose Businesshub as station API)
2. Go to https://marudor.de/Schorndorf  
or type "Schorndorf" to the search field.

**Expected behavior**
Data of Schorndorf is being diaplayed. "Schorndorf" is written to the search field.

**Screenshots**
![image](https://user-images.githubusercontent.com/19571454/89432208-20b80b80-d741-11ea-97fc-822503feceaf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome, Edge, Firefox

**Comment by marudor** [comment]
Wow. apparently "Schorndorf" is a better match for "Dortmund Hbf" than "Schorndorf" actually is..
I'm going to add a exact match addition. So if your search is matched completly it will use the exact match instead of whatever the API thinks is the best match.
