### ISSUE TITLE
Log/Store all delays

### ISSUE THREAD

**Issue by mhombach** [marudor/BahnhofsAbfahrten#39]
My feature proposal is to log and store all delays.
The reason is to be able to have those information in case of depending on the "Mobilitätsgarantie".
I an since 2 months fighting with a train company because they seem to have no way of getting the (correct) information about huge delays in their schedule days or weeks after.
I'm open about the details, like, if only the last delay-information is stored or if the history is stored also (5min delay, 10min delay, 20min delay, oh now it's completely canceled).
If needed i can help with providing some database storage.

**Comment by derhuerst** [comment]
I'm aware that the following tools are not compatible with the `BahnhofsAbfahrten` APIs, but check out these:

- https://github.com/public-transport/hafas-client – JavaScript client for HAFAS public transport APIs.
- https://github.com/derhuerst/db-hafas – JavaScript client for the Deutsche Bahn HAFAS API. (wrapper around `hafas-client`)
- https://github.com/derhuerst/hafas-record-delays – Record delays from hafas-monitor-departures into a LevelDB.
- https://github.com/derhuerst/hafas-monitor-departures – Pass in a HAFAS client, fetch all departures at any set of stations.
- https://github.com/derhuerst/hafas-monitor-trips – Using a HAFAS endpoint, watch all trips in a bounding box.

**Comment by marudor** [comment]
Either use what @derhuerst suggested or use the API to build it yourself. (docs.marudor.de, WIP documentation)
There is also zugfinder.de that does basically that.
Defintively out of scope for this project.
