### ISSUE TITLE
Zugsuche fehlerhaft

### ISSUE THREAD

**Issue by tciberlin** [marudor/BahnhofsAbfahrten#398]
Die Suche eines Zuges anhand der Zugnummer führt zu einem Fehler. Dieses wurde seit gestern mit mehrere. Zugnummern probiert, was alles zu dem selben Resultat führte:
![image](https://user-images.githubusercontent.com/3908961/90335541-fd5d4e00-dfd5-11ea-9cc1-a156965d0970.png)

**Comment by marudor** [comment]
Welche URL ist das? Vermutlich hast du einen anderen HAFAS provider eingestellt.

**Comment by tciberlin** [comment]
Eigenartigerweise funktioniert es jetzt wieder, ohne Änderungen in den Einstellungen.
