### ISSUE TITLE
Implement "Homebutton" everywhere

### ISSUE THREAD

**Issue by TheRojam** [marudor/BahnhofsAbfahrten#40]
**Is your feature request related to a problem? Please describe.**
Everytime i'm on routing i need to reload the site or get two times back.

**Describe the solution you'd like**
I would like to have an "homebutton" to get switch to train search or stationview or to the startpage back.

**Describe alternatives you've considered**
ATM i have no other considerations.

**Additional context**
Like on the startpage.

**Comment by marudor** [comment]
Will collect all issues related to an UX Concept in #51
