### ISSUE TITLE
ÖBB Wagenreihung

### ISSUE THREAD

**Issue by j-f-j** [marudor/BahnhofsAbfahrten#405]
Die ÖBB bieten unter https://live.oebb.at eine Plattform an über die eine Wagenreihung abgefragt werden kann.

Example: https://live.oebb.at/stat?name=IC%20518&stationEva=8100070&departure=30.08.2020
JSON GET Request dahinter führt zu https://live.oebb.at/backend/api/train/IC%20518/stationEva/8100070/departure/30.08.2020

**Comment by marudor** [comment]
"Wir bitten um Entschuldigung. Aktuell funktioniert die Abfrage nach Zugverbindungen nicht. Bitte versuchen Sie es zu einem späteren Zeitpunkt erneut"
Fängt gut an.

Mal morgen schauen.

**Comment by marudor** [comment]
bb3c4cac9fb0cdffb57ae95f57a2a9edf35ab119 hat damit jetzt mal angefangen. War ja quasi "morgen"
Ist noch nicht perfekt, aber immerhin ein Anfang. Die Daten sind leider auch nicht immer top, grade was die Position des Zuges betrifft. Aber besser als nichts vermute ich mal. Wird jetzt weiter entwickelt, ich mach das hier damit mal zu.

Wird später dann auf marudor.de released, vorerst nur auf beta.marudor.de
