### ISSUE TITLE
Zug doppelt angezeigt bei Umleitung in anderen Bahnhofsteil

### ISSUE THREAD

**Issue by ip138** [marudor/BahnhofsAbfahrten#423]
Beispiel siehe Screenshot: S-Bahn endete außerplanmäsig Stuttgart Hbf oben = Stuttgart Hbf (tief) entfällt, Stuttgart Hbf oben zusätzlicher Halt = doppelte Anzeige (weil betrieblich zwei Bahnhöfe?) 
![Screenshot_20201007-172023_Chrome](https://user-images.githubusercontent.com/19571454/95352405-80a66c00-08c2-11eb-9060-2d0410df2c08.jpg)

**Comment by marudor** [comment]
Noch als Kurze Info - es gibt die Unterscheidung Haltestelle und Station.
Station = Ein oder mehrere Haltestellen
Haltestelle = Ein halt

Die Station Stuttgart Hbf besteht aus den Haltestellen Stuttgart Hbf und Stuttgart Hbf (tief)
