### ISSUE TITLE
Alarm / Push notification for delays

### ISSUE THREAD

**Issue by SAMUD** [marudor/BahnhofsAbfahrten#43]
**Is your feature request related to a problem? Please describe.**
Sometimes the DB trains are to late ;)

**Describe the solution you'd like**
The push notifications for delayed trains in the DB Navigator and DB Streckenagent don't work really reliable. It would be cool to be able to set alarms for specific train numbers and specific time frames.
For example remind me if train SWE88449 is delayed (or there is any other problem) and it's Mo-Fr.

**Describe alternatives you've considered**
I tried to use the car. But driving a car in rush hour is not very fun.

**Additional context**

**Comment by marudor** [comment]
As Push notifications do not work for iOS without having an ap pright now this won't happen for now.
If someone wants to build a native app feel free. I do not really have capacity for that.

Once iOS has the ability to push via service worker I will most likely implement it.

**Comment by derhuerst** [comment]
cc @alexander-albers

**Comment by alexander-albers** [comment]
I wanted to add such a feature to my app for a long time now. Is there any other way to implement such a feature apart from refreshing the journey details every x seconds for every saved delay alarm?

**Comment by derhuerst** [comment]
> Is there any other way to implement such a feature apart from refreshing the journey details every x seconds for every saved delay alarm?

If you mean other than refreshing the journey *on the client*: Yes, we can set up a server to do this.

If you mean other than having *anything fetching* the journey periodically: HAFAS has a push notification feature, where they push semi-helpful messages to the apps directly; you can try it out in e.g. the DB Navigator or VBB apps.

**Comment by alexander-albers** [comment]
Refreshing the journey on a client wouldn’t work on iOS anyway, as you cannot tell the os when or how often the app should be invoked. Refreshing the journey on a server would make me worry that hafas could reject too many requests from the same IP address.

Regarding the push notification feature, are you referring to https://fahrinfo.vbb.de/cmi/subscriptions/save? It seems to me that this does only work for apps under development by hafas, as they need to specify the bundle/app id of the receiver app when sending a push message.

**Comment by SAMUD** [comment]
@marudor: ditch iOS. On Android you can add notifications for websites. :P

@alexander-albers: ohhh. Another iOS only app :(

**Comment by derhuerst** [comment]
> Regarding the push notification feature, are you referring to https://fahrinfo.vbb.de/cmi/subscriptions/save? It seems to me that this does only work for apps under development by hafas, as they need to specify the bundle/app id of the receiver app when sending a push message.

It [looks](https://gist.github.com/derhuerst/5ed5fc1640661937d080c271d45e17ee#file-03-set-alarm-http-L12-L60) [like it](https://gist.github.com/derhuerst/103619620a0be00fcb225b80859a62ce#file-02_-http-L11), unfortunately.

**Comment by marudor** [comment]
Nowadays I've got https://docs.marudor.de/#tag/HAFAS-Subscribe (as usual I do not have usage documentation, I'm not documenting hafas here)
notifications to marudor will not be there until major platforms (as in iOS and android) support it. I dislike doing features that only work in one of those platforms.

**Comment by alexander-albers** [comment]
Hi, does that mean that you figured out how to receive push notifications from hafas directly to your server?

**Comment by derhuerst** [comment]
I head that there's an entirely separate API, HAFAS Push Server, that allows you to define a webhook that will be called.

**Comment by alexander-albers** [comment]
Ah I see, interesting.. thanks for the info.
