### ISSUE TITLE
More options regarding LOK info.

### ISSUE THREAD

**Issue by 74Brasilia** [marudor/BahnhofsAbfahrten#431]
**Describe the solution you'd like**
On the departures screen, could you add a feature to display LOK number(s), without having to click on each individual train to display this information? Perhaps add a toggle to turn this feature on in the settings?

Like Zugsuche, perhaps you could have a LOKsuche too, so that if for example 101 136-0 is on IC 2311 as it currently is, this information could be returned if a search for 101 136-0 was performed?

Alternatively, a list of all LOKs, 101, 146, 147, 218, 401, 402 etc that are currently allocated to passenger train(s), with the train(s) listed for each individual LOK?

**Comment by marudor** [comment]
Technically there is a way for this already. But as it's super inperformant I only use it for debugging. Once I have a way to do this faster I plan on have that.
