### ISSUE TITLE
Routing only nahverkehr

### ISSUE THREAD

**Issue by xCuzImPro** [marudor/BahnhofsAbfahrten#44]
pls add in the Routing option, the option of only Nahverkehr.

**Comment by PDesire** [comment]
@marudor Is that even possible ? I parse my HAFAS data via @schildbach his public-transport-enabler, and there was no option for that too. Maybe it's some extra module for DB ?

**Comment by derhuerst** [comment]
All HAFAS endpoints have allow you to exclude certain "products". *Which* depends on the endpoint.

The specific "nur Nahverkehr" option on `bahn.de` just send `journeyProducts=1016`, which is the bitmask for no long-distance products:

```js
const parse = require('hafas-client/parse/products-bitmask')
const dbProfile = require('hafas-client/p/db')

console.log(parse(dbProfile)(1016))
```

```js
{
  nationalExpress: false,
  national: false,
  regionalExp: false,
  regional: true,
  suburban: true,
  bus: true,
  ferry: true,
  subway: true,
  tram: true,
  taxi: true
}
```

**Comment by marudor** [comment]
Yep as @derhuerst said. It's possible. I just didn't have time for it yet.
