### ISSUE TITLE
False positive for ICE 1 LDV

### ISSUE THREAD

**Issue by MarkMcWire** [marudor/BahnhofsAbfahrten#447]
You marked the ICE units 154 "Flensburg" and 157 "Landshut" as ICE 1 LDV. Thats not the case. Both Tz have only been shortened, but have not received a LDV. The service car 803.1 is still first class among the shortened multiple units. At the LDV he's second class.

LDV are 155 "Rosenheim", 179 without a name, 180 "Castrop-Rauxel" (is currently in NNRX for LDV) and 102 "Jever" (is currently in NNRX for LDV)

Shortened but not LDV: 154 "Flensburg", 157 "Landshut"

Greating from Eisenach

* NNRX = DS100 code for Nuremberg maintance

**Comment by marudor** [comment]
Is noted. Will fix that soonish.
