### ISSUE TITLE
show kilometers between the stations in the routing part

### ISSUE THREAD

**Issue by asraelvudogel** [marudor/BahnhofsAbfahrten#45]
It would be nice, if you can show the kilometers between the stations in the routering part of marudor.de, if any of the API you use has this parameter.
Especially for tickets that are limited to a certain number of kilometers, it would be good to know if you can ride this route with it.

**Comment by marudor** [comment]
Sadly no API has this so far. All I would be able to add would be a calculation on my own. Which especially for your ticket case wont help as its not a official number.
