### ISSUE TITLE
Style of vehicle group number

### ISSUE THREAD

**Issue by MarkMcWire** [marudor/BahnhofsAbfahrten#457]
A friend of mine who works in the Frankfurt operations center has pointed out a display error.
For RPFx nnnnn there should be a space between RP, Fx and nnnn.

RP is the abbreviation for Riga-Park, i.e. a fixed fleet of vehicles. Fx stands for the respective fleet management, F8 is the headquarters in Frankfurt, F1 stands for Fleet Management Hamburg, for example. The numbers are also stored in the train formation plan.

And nnnnn is the number of the vehicle fleet.

So the format should be "RP Fx nnnnn".

Thx.

**Comment by MarkMcWire** [comment]
Kennung Bereich
F1 Nord (Hamburg)
F2 Ost (Berlin)
F3 not in use anymore (Hannover)
F4 West (Dortmund)
F5 Mitte (Frankfurt)
F6 not in use anymore (Karlsruhe)
F7 Süd (München)
F8 Zentrale

**Comment by marudor** [comment]
Well, that format is straight from the Bahn API.
Guess I have to do formatting then.
Noted, low priority though.
