### ISSUE TITLE
Weitere Zug Typen Filteroptionen 

### ISSUE THREAD

**Issue by MundMBo** [marudor/BahnhofsAbfahrten#458]
Nur ein weiteres nice2have Feature

**Szenarien und bisheriges Vorgehen**
- Suche nach einer Abfahrt eines ICE 3: Aufrufen der nächsten Abfahrten, bestmögliche Filter werden gesetzt, die nächsten Züge werden einzeln angeklickt und es wird geprüft, ob Zug bestimmte Kriterien erfüllt 
- Suche nur nach Fernverkehr Zügen: 5 Filter einzeln deaktivieren
- Suche nach einer Abfahrt des Metropolitan (MET): Suche nach aktueller Auflistung der MET Zugnummern (z.B. hier: https://de.wikipedia.org/wiki/Metropolitan#Fahrzeugeinsatz_ab_15._Dezember_2019), suche nach Abfahrt des Zuges

**Lösungsansatz**
hierarchisches ausklappbares Menü mit 3 state Checkboxen
Level 1 und 2 des Menüs standardmäßig ausgeklappt, tiefere Level standardmäßig eingeklappt
Aktivieren/Deaktivieren von Checkboxen höherer Level überschreibt Checkboxen tiefere Level 
Filtern der angezeigten Züge entsprechend ausgewählter Filter

**Beispielhafter Aufbau**
- Fernverkehr
   - ICE
       - ICE 1
       - ICE 2
       - ICE 3
       - ICE T
       - ICE 4
   - IC
       - IC 1
       - IC 2
   - EC
   - MET
- Nahverkehr
    - RE
    - RB
    - S
    - ...

**Bisher**
![Screenshot_20210119_195805_com android chrome](https://user-images.githubusercontent.com/45039833/105081510-96672800-5a92-11eb-8a22-9c6d65f31cdc.jpg)

**Mockup neu**
![Screenshot_20210119_195805_com android chrome_new](https://user-images.githubusercontent.com/45039833/105087931-83a52100-5a9b-11eb-822e-d6b9e3eb9888.jpg)

**Comment by marudor** [comment]
ICE Trennung nicht möglich. Die Info gibts nur in der Wagenreihung - und das für jeden an der Stelle holen ist nicht möglich - performance würde stark leiden.

**Comment by MundMBo** [comment]
schade, trotzdem danke für die Rückmeldung.
