### ISSUE TITLE
Ril100 / DS100 code for "Erfurt Hauptbahnhof" don't work.

### ISSUE THREAD

**Issue by MarkMcWire** [marudor/BahnhofsAbfahrten#466]
If you try to use "UE" as Code for Erfurt Hbf, you get Uelzen but no Erfurt.

Official Code is "UE P" for "Erfurt Hauptbahnhof Bahnhofsteil Personenbahnhof" in contrast to "UE G" for "Erfurt Hauptbahnhof Bahnhofsteil Güterbahnhof"

But "UE P" don't work, too.

Greating from Eisenach

**Comment by MarkMcWire** [comment]
Is back again. "UE" oder "UE P" don't work.

**Comment by marudor** [comment]
Current source  does not know UE for Erfurt - it knows UE  P (two spaces)
Sadly that is apparently broken right now I guess I handle that double space wrongly.

I'm currently reworking the whole search so it will be broken until I'm done with that.

**Comment by marudor** [comment]
As I'm not using RL100 often - should I support UE P with one space and UE  P with two spaces?
As far as I know officaly its with two spaces. But I guess in day to day use its often with one space?

**Comment by marudor** [comment]
fixed again.
