### ISSUE TITLE
No location info for stations anymore?

### ISSUE THREAD

**Issue by derwaldgeist** [marudor/BahnhofsAbfahrten#473]
Since a couple of days, the station search does not return any location info (lat, lon) any more:

https://marudor.de/api/station/v1/geoSearch?lat=49.05395085&lng=8.521892562572518

The stations are still there, but the `location` property is missing.

Any chance to get this back?

(Previously, the values also included `ds100` and `stada` values, which are gone as well. We don't need them, so we don't care about them. But I wanted to mention this, just in case.)

**Comment by marudor** [comment]
Oh, location being gone was not supposed to happen. Gonna fix that.

**Comment by marudor** [comment]
Although - it was never part of the API Spec (Thats why I didn't notice that)
Anyway, I rolled back the release of friday that broke this and will fix it.

**Comment by derwaldgeist** [comment]
@marudor Hey, thanks a million for bringing this feature back in such a short time, that's amazing! Any chance to get this "officially" supported?

**Comment by marudor** [comment]
Thats already on beta. (beta.docs.marudor.de)
Could you check real quick if you can work with that? On beta it will include ÖPNV stations. Therefore I will have way more stations.

**Comment by derwaldgeist** [comment]
That sounds amazing! Currently, I only get a cert error when trying to access the site. I guess you are working on it and that's why it is down?

**Comment by derwaldgeist** [comment]
Will the Beta also include geo-information for the ÖPNV stations? That would be awesome!

**Comment by marudor** [comment]
https://docs.beta.marudor.de/
wrong order of beta and docs 
Yes it does include location for ÖPNV

**Comment by derwaldgeist** [comment]
Wow, thanks a lot! Tried it out, works as a charm!

Will the endpoint `beta.marudor.de` stay active, or shall we better wait until it gets into production?

**Comment by marudor** [comment]
Dont use beta - prod will be there in about 5 minutes.

**Comment by derwaldgeist** [comment]
Ok, awesome, thanks for the info!

One additional question:

To get the actual departures, we currently hand over the station name like this: 

https://marudor.de/Frankfurt(Main)Hbf

However, this yields no results for the ÖPNV stations:

https://beta.marudor.de/Burgstra%C3%9Fe%20Weingarten%20Baden

(In general, handing over the station name seems a bit error prone to me. So I was wondering if there is an way to retrieve the departures: using the internal station IDs which I get over the station API?)

**Comment by marudor** [comment]
Abfahrten do not work for ÖPNV.
Station names are not error prone as long as you use the name you get from my API - that will work.

**Comment by derwaldgeist** [comment]
> Abfahrten do not work for ÖPNV.

Oh, that's a bummer for our use-case, since we are using the stations API to first retrieve the stations and then show the departures in the "real world". Any chance to get this in? If not, is there at least a way to tell which of the stations are actually ÖPNV, so we could suppress these? Otherwise, there will be a lot of cases where the people would see a station, but can't get the actual departures, which is frustrating.

**Comment by marudor** [comment]
For now: filter out everything that has evaNumber stating with 0.
I've got some refactoring planned that will fix this.

**Comment by marudor** [comment]
You could redirect people to https://marudor.de/regional/Arndt-%2FSpittastra%C3%9Fe%2C%20Stuttgart for everything starting with 0. (Regional has ÖPNV but is less accurate)

**Comment by derwaldgeist** [comment]
Wow, that's great, wasn't aware of that regional endpoint.

Just for clarification: is the EVA number the same that is reported as "id" in the stations API? I am asking because our DB station here also has a number starting with "0", and that works with the normal departures (maybe because it's also an ÖPNV stop?).

You can see it here in this dataset:

https://beta.marudor.de/api/station/v1/geoSearch?lat=49.05395085&lng=8.521892562572518

The first one is the DB station, the others are bus stops. All start with a 0.

**Comment by derwaldgeist** [comment]
Sorry, my error. All are bus stops. But the DB station is actually gone now. Any idea why this may have happened? It was called "Weingarten (Baden").

**Comment by marudor** [comment]
Increase the radius. Default ist 500m.

**Comment by derwaldgeist** [comment]
Oh, you are absolutely right. My bad. I thought the location was actually at the station, because "Bahnhof (Ost)" was included (which is on one side of the station). But obviously, the actual station was just a bit beyond the radius. Thanks a lot for your support, and sorry for bothering :-)

**Comment by derwaldgeist** [comment]
BTW: We're currently using the DB logo in our app. However, as the data is actually coming from your service, I was wondering if there is an official "Marudor" logo we could include instead, so we can give you the credits you definitely deserve? This is such an amazing service, and we want to honor that.

**Comment by marudor** [comment]
Technically I have no license to distribute the data - so feel free to use me and not credit me. Data is provided by DB after all.

**Comment by derwaldgeist** [comment]
Thanks, that's nice.

One feedback: While testing, I noticed there are stations that have an id starting with 8, but don't have a departure on the "national" endpoint. A sample from this dataset:

https://marudor.de/api/station/v1/geoSearch?lat=50.9432141&lng=6.9586017

is "Köln Hbf (Breslauer Platz)", with the id 8089322.

This works:
https://marudor.de/regional/K%C3%B6ln%20Hbf%20(Breslauer%20Platz)

but not this:
https://marudor.de/K%C3%B6ln%20Hbf%20(Breslauer%20Platz)

Maybe this is because it's the rear exit of the Kölner Hauptbahnhof?

**Comment by marudor** [comment]
meh - I knew tas thats just a workaround. Will filter geoSearch again so it behaves similar to what id did before my changes. ÖPNV will be back with my refactoring.

**Comment by derwaldgeist** [comment]
I would actually prefer if you keep it like it is for now, having the ÖPNV is awesome, and we can live with the edge cases.

**Comment by marudor** [comment]
Okay, in that case it stays like this for now

**Comment by derwaldgeist** [comment]
Thanks!
