### ISSUE TITLE
Station IDs with less than 6 digits do not work via the API

### ISSUE THREAD

**Issue by KristjanESPERANTO** [marudor/BahnhofsAbfahrten#479]
If I use IDs with less than 6 digits, I get the following error message: `StationBoard HAFAS Error`

Example query:
https://marudor.de/api/hafas/v2/departureStationBoard?station=5095?profile=insa

With IDs with at least 6 digits, it works.

Example query:
https://marudor.de/api/hafas/v2/departureStationBoard?station=8000107?profile=insa

I tried many IDs, always with the same result. The IDs are correct, I also use them with the insa profile in another project with the `hafas-client`.

The insa profil has a lot of "short" IDs: https://marudor.de/api/hafas/v1/station/freiim?profile=insa

**Comment by marudor** [comment]
Oh, I refactored it because I really though they all use evaNumbers as ids...
Will fix later.

**Comment by KristjanESPERANTO** [comment]
That was quick. Thank you!

Is an old version running on your demo server? Because the error still occurs there: https://marudor.de/api/hafas/v2/departureStationBoard?station=5095?profile=insa

**Comment by marudor** [comment]
Check your URL...
Your query parameter are wrong. (Only one ?, rest should be with &)

**Comment by KristjanESPERANTO** [comment]
Oh, thank you! :smile:
