### ISSUE TITLE
Umlaute in Bahnhofsnamen

### ISSUE THREAD

**Issue by calvin5375** [marudor/BahnhofsAbfahrten#486]
**Describe the bug**
Mahlzeit,
bei Bahnstationen, die als Favoriten gesetzt sind und einem Umlaut wie ä, ö und ü im Namen haben, werden diese nach mehrfachem Neuladen der Seite mit Kombinationen wie "Ã" oder "Â¼" ersetzt.

**To Reproduce**
1. "Düsseldorf Hbf" als Favorit setzen.
2. In die Ansicht "Abfahrten" gehen.
3. Mehrmals Seite aktualisieren.

**Expected behavior**
Ich würd behaupten da sollten eher die Umlaute angezeigt werden :D

**Screenshots**

![PXL3XLB](https://user-images.githubusercontent.com/47431901/114390567-b6405080-9b96-11eb-8e2c-d6a32bf48c85.png)

![Win10A](https://user-images.githubusercontent.com/47431901/114390583-be988b80-9b96-11eb-939c-e7eeaddd8a03.png)

![PXL3XLD](https://user-images.githubusercontent.com/47431901/114390686-dd971d80-9b96-11eb-8437-07c7ef811c7a.png)

**Desktop:**
 - OS: Windows 10 (20H2)
 - Browser: [Chrome]
 - Version: [89.0.4389.114]

**Smartphone:**
 - Device: [Google Pixel 3 XL]
 - OS: [Android 11 (RQ2A.210305.006)]
 - Browser [Chrome]
 - Version [89.0.4389.105]

**Additional context**
Die ersetzten Zeichen multiplizieren sich mit jedem refresh der Seite erneut und glitchen je nach Bildschirmgröße über den Bildschirmrand hinaus. 

Sobald ein Umlaut ersetzt wurde, kann die entsprechende Abfahrtstafel auch nicht mehr geladen werden.
![Win10B](https://user-images.githubusercontent.com/47431901/114390630-cbb57a80-9b96-11eb-8545-60aabbe582e4.png)

**Comment by marudor** [comment]
fixed. Betroffene favs löschen, und neu anlegen
