### ISSUE TITLE
Remaining time until departure

### ISSUE THREAD

**Issue by Bergiu** [marudor/BahnhofsAbfahrten#490]
Es wäre praktisch einen zusätzlichen Timer neben den Abfahrtszeiten anzuzeigen, welcher angibt in wie viel Minuten der Bus fährt. Die Webseite läuft hier auf einem Bildschirm im Eingang und durch das Feature kann man mit einem kurzen Blick auf den Bildschirm sehen wie viel Zeit man noch hat um den Bus zu bekommen.

**Comment by marudor** [comment]
Hab ne Weile überlegt und mich entschieden mich aufs wesentliche zu konzerntrieren => wenige UI Optionen.
