### ISSUE TITLE
Info: neue RIS-Infotexte ab 30.09.21

### ISSUE THREAD

**Issue by tciberlin** [marudor/BahnhofsAbfahrten#499]
Hallo, ab dem 30.09. sollen neue Begründungen/Formulierungen für Verspätungen / Qualitätsabweichungen bei der Bahn eingeführt werden. Eine Übersicht gibt es hier

https://www.dbnetze.com/resource/blob/6245806/1c422761486d3bf7c4f430ad857db793/2021_24_Liste_optimierte_RIS-Kundengruende-data.xlsx

Das ganze nur zur Info, da ich nicht weiß in wie weit das bei Dir in die Programmierung mit eingebunden werden muss.

**Comment by marudor** [comment]
Danke, ja die werd ich bei mir anpassen. Klingen tatsächlich auch besser.
Vielleicht bau ich die auch schon früher ein.

**Comment by marudor** [comment]
Ich korrigiere. Ich habs jetzt schon angepasst. Dann vergess ichs nicht - und die Texte sagen ja effektiv das gleiche aus.
