### ISSUE TITLE
ÖPNV stopPlaces search returns duplicates

### ISSUE THREAD

**Issue by ip138** [marudor/BahnhofsAbfahrten#500]
**Describe the bug**
ÖPNV search returns the same stop place multiple times with the same name and the same departures in the end. 

**To Reproduce**
1. Go to [https://marudor.de/regional](https://marudor.de/regional)
2. Search for "Arndt-/Spittastraße"
3. See 3 suggestions with the same name "Arndt-/Spittastraße, Stuttgart"
4. Same (correct) departure results after clicking at each row

**Expected behavior**
Result names are unique.

**Desktop (please complete the following information):**
 - OS: many
 - Browser: many

**Additional context**
Changed most likely with the integration of the new StopPlaces search, commit f34acf40a6ca075d71c355dd43cf36a5de139cea. The API result ([https://marudor.de/api/stopPlace/v1/search/Spittastraße](https://marudor.de/api/stopPlace/v1/search/Spittastra%C3%9Fe)) implies that there are multiple entries for the same stop place, but with different EVA numbers and slightly different positions (a few metres) - so I'm not sure it's logically correct to make them unique by name?

**Comment by marudor** [comment]
Well it's technically correct that there are 3 different ones. But they are grouped together for departures.
So not really a bug. More of a feature request to also group the search.
