### ISSUE TITLE
Show modernized IC 1 wagon.

### ISSUE THREAD

**Issue by DerChaot** [marudor/BahnhofsAbfahrten#501]
**Is your feature request related to a problem? Please describe.**
Some people might like the new seats better on the old IC 1 and with this feature they can find them easier without traveling through the whole IC. I for one like the old seats in the IC 1 as you can recline them so that you can sleep in them fairly well. 
But it would be a cool feature none the less as this information seems to be out there. (see next point)

**Describe the solution you'd like**
When I click on an IC in your station overview I would like to see if any wagons are modernized with new seats and interior.
So that it look similiar to this http://www.grahnert.de/fernbahn/reihung/r211-2300.pdf.
It would spare me the time to look up the train number on the linked website.

**Describe alternatives you've considered**
You don´t implement it and I would have to look it up on grahnert.de.

**Comment by marudor** [comment]
Already existing. Bpmmz and so on, double m = modernized.
Thats all the data there is for real time data.
