### ISSUE TITLE
Inkonsistentes Verhalten bei im RV wechselnden Zugzielen

### ISSUE THREAD

**Issue by TheMinefighter** [marudor/BahnhofsAbfahrten#502]
Wenn man im Regionalverkehrabfahrtsmonitor einen Zug betrachtet der während seines Laufwegs das Zugziel wechselt, so wird dort das endgültige Zugziel angezeigt. Wenn man dann aber auf den Zug klickt wird nur der Laufweg bis zu der Station angezeigt, die an der betrachteten Station auf dem ZZA steht, was inkonsistent mit dem anderen Verhalten ist und zu Verwirrung führen kann.
Beispiel: in RKDT fährt eine S-Bahn ab die bis TPH als S5, danach weiter als S6 nach TWBK. Wenn man in RKDT auf die Abfahrten schaut steht TWBK drinn, wenn man auf "Details" klickt steht da TPH als Ziel. Siehe Screenshots
![Screenshot_20210706-141949_Firefox.png](https://user-images.githubusercontent.com/32145868/124600413-f7c75b80-de66-11eb-92a3-9a87f9eafe78.png)
![Screenshot_20210706-141959_Firefox.png](https://user-images.githubusercontent.com/32145868/124599886-77a0f600-de66-11eb-8dd9-968b7b246c4f.png)

**Comment by marudor** [comment]
Nicht lösbar, das liegt an unterschiedlichen Datenquelen.
Details sind HAFAS, dort wird das so umgesetzt das der Zug seine Nummer ändert, passiert auch nicht immer.
Würd ich gern vereinheitlichen, geht aktuell aber nicht.
