### ISSUE TITLE
Funktion "Neue Abfahrt bei Verspätung" lässt sich nicht mehr deaktivieren

### ISSUE THREAD

**Issue by bridgerdier** [marudor/BahnhofsAbfahrten#507]
**Describe the bug**
Alle angezeigten Zeiten behinhalten plötzlich die fiktiven Verspätungsprognosen

**To Reproduce**
Sowohl in den Bahnhofsabfahrten als auch im Zuglauf. Die Einstellung "Neue Abfahrt bei Verspätung" ist aus den Einstellungen verschwunden

**Expected behavior**
Die veröffentlichte Abfahrtzeig ist eine wichtige Referenz, die fiktive Zeit ist verwirrend, wenn die Verspätungsprognose darunter steht: "15:31 +41 heißt um 16:31, oder?"

**Comment by marudor** [comment]
Absichtlich entfernt.
Die frühere default Option ist jetzt die einzige.
Es steht immer die reale Zeit da.
Sprich 15:31 +41 => 15:31 wird abgefahren, plan war 15:31 - 41 Minuten also 14:50.

**Comment by bridgerdier** [comment]
Also ist die Plan-Abfahrtzeit, nach der die Liste sortiert ist und die auf den Bahnsteig-Anzeigern und Info-Monitoren angezeigt wird, nirgends mehr ersichtlich? :(

Damit ist die Seite für mich leider nicht mehr benutzbar. Wird Zeit, über einen Fork nachzudenken *grummel*

**Comment by marudor** [comment]
Viel spaß beim forken.
