### ISSUE TITLE
Connection of the Mitteldeutsche-Regiobahn-API

### ISSUE THREAD

**Issue by frankenstein91** [marudor/BahnhofsAbfahrten#510]
I would be happy if the API of the Mitteldeutsche Regionalbahn could be included in the website. This is a reliable source for the delays and train compositions of the MRB.

Link to the API: https://www.mitteldeutsche-regiobahn.de/de/abfahrtsmonitor.json

How I use it:
`curl 'https://www.mitteldeutsche-regiobahn.de/de/abfahrtsmonitor.json' -H 'Accept: application/json' --compressed -H 'Content-Type: application/json;charset=utf-8' --data-raw '{"station":"LGRI","offset":0}'| python -m json.tool`

**Comment by marudor** [comment]
https://marudor.de/api/iris/v2/abfahrten/ (iris) should already include delays.
https://marudor.de/regional most likely does not have the same quality. But I'm currently not focused on adding non HAFAS APIs here.

Train compositions of MRB are not really accurate (Only BR like 650 for Stadler_Regio-Shuttle_RS1 for instance)
Thats more than I currently support but I would rather not add a new API that adds little value for now.

So for now I would not add this.
If you have additional information that might change this feel free to add them.

**Comment by frankenstein91** [comment]
Hi @marudor 

as far as I know, the delays are not reported to any other API. Not even the route planners of the Deutsche Bahn and the Verkehrsverbund know this information. https://marudor.de/api/iris/v2/abfahrten/8011705 could not provide me with any information about the train at the time of execution.

```
        {
            "status": "puenktlich",
            "departure": "2021-08-09T10:26:00.000+02:00",
            "forecast": "2021-08-09T10:26:00.000+02:00",
            "departure_time": "10:26",
            "forecast_time": "10:26",
            "delay": 0,
            "transport": "27723 - 110",
            "direction": "Leipzig Hbf",
            "cancellation": false,
            "traction": [
                {
                    "fzgposition": "1",
                    "fzgtyp": "643",
                    "ziel": "Leipzig Hbf"
                }
            ],
            "intermediate_stations": [
                {
                    "id": "LGS",
                    "name": "Gro\u00dfsteinberg",
                    "departure": "2021-08-09T10:32:00.000+02:00",
                    "departure_time": "10:32",
                    "forecast": "2021-08-09T10:34:00.000+02:00",
                    "delay": 2
                },
                {
                    "id": "LNH",
                    "name": "Naunhof",
                    "departure": "2021-08-09T10:37:00.000+02:00",
                    "departure_time": "10:37",
                    "forecast": "2021-08-09T10:38:00.000+02:00",
                    "delay": 1
                },
                {
                    "id": "LBEU",
                    "name": "Beucha",
                    "departure": "2021-08-09T10:42:00.000+02:00",
                    "departure_time": "10:42",
                    "forecast": "2021-08-09T10:43:00.000+02:00",
                    "delay": 1
                },
                {
                    "id": "LBOR",
                    "name": "Borsdorf (Sachs)",
                    "departure": "2021-08-09T10:46:00.000+02:00",
                    "departure_time": "10:46",
                    "forecast": "2021-08-09T10:47:00.000+02:00",
                    "delay": 1
                },
                {
                    "id": "LEH",
                    "name": "Engelsdorf Hp",
                    "departure": "2021-08-09T10:50:00.000+02:00",
                    "departure_time": "10:50",
                    "forecast": "2021-08-09T10:51:00.000+02:00",
                    "delay": 1
                },
                {
                    "id": "LLPD",
                    "name": "Leipzig-Paunsdorf",
                    "departure": "2021-08-09T10:53:00.000+02:00",
                    "departure_time": "10:53",
                    "forecast": "2021-08-09T10:54:00.000+02:00",
                    "delay": 1
                },
                {
                    "id": "LSEH",
                    "name": "Leipzig-Sellerhausen",
                    "departure": "2021-08-09T10:55:00.000+02:00",
                    "departure_time": "10:55",
                    "forecast": "2021-08-09T10:56:00.000+02:00",
                    "delay": 1
                },
                {
                    "id": "LL",
                    "name": "Leipzig Hbf",
                    "departure": "2021-08-09T11:00:00.000+02:00",
                    "departure_time": "11:00",
                    "forecast": "2021-08-09T11:00:00.000+02:00",
                    "delay": 0
                }
            ],
            "info": []
        }
```

![Screenshot 2021-08-09 at 08-58-55 RB 110 09 08 2021](https://user-images.githubusercontent.com/2527348/128670365-c4383245-2b64-42cd-8e34-8c54cb890804.png)

**Comment by marudor** [comment]
Like I explained, trainComposition is out  of scope as its not enough data for my current visualizations.

**Comment by frankenstein91** [comment]
@marudor but the delays are missing too... as you can see

**Comment by marudor** [comment]
Youre showing a screen of details, not iris. Details is HAFAS (DB Navigator)
Only the Departure board has delays.

**Comment by frankenstein91** [comment]
> https://marudor.de/api/iris/v2/abfahrten/8011705 could not provide me with any information about the train at the time of execution.

However, the lead time is much higher for the MRB API.
