### ISSUE TITLE
Only one train shows up in coupled configuration.

### ISSUE THREAD

**Issue by DerChaot** [marudor/BahnhofsAbfahrten#537]
**Describe the bug**
For some coupled trains, only one train is shown.

**To Reproduce**
Search for a station, in my case Göttingen and search for two trains, which are coupled. In some cases one train is missing in the graphic. Clicking on their detail page does not help and both trains only show the same train with the same carriage number.

![Screenshot_20211117_130924](https://user-images.githubusercontent.com/19267144/142211807-84836151-9da2-42a0-9edd-e253a667bec4.png)
![Screenshot_20211117_130954](https://user-images.githubusercontent.com/19267144/142211842-e7e7b9a0-2aa9-4b2f-93dc-e7c12b2383bf.png)
![Screenshot_20211117_131015](https://user-images.githubusercontent.com/19267144/142211852-f7f19d32-8ede-407e-a4d9-3e9cdd5b60a3.png)
![Screenshot_20211117_131026](https://user-images.githubusercontent.com/19267144/142211862-ef330522-e703-490f-892c-6fa7bfab7854.png)

**Expected behavior**
Two trains should appear in their correct way.

**Screenshots**

**Desktop (please complete the following information):**
 -Firefox, Linux

**Comment by marudor** [comment]
Not fixeable. Whatever the API returns is displayed.

**Comment by DerChaot** [comment]
I just checked one of these errors in the DB Navigator.
It says at the bottom "Train deviates with only one train. The carriages 21-27 are not present."
Should'nt this mean that the whole second train is cancelled?

I guess it is not shown as cancelled, as they normally would part in Hannover and the stations after that are cancelled for the missing train. 
So this is just one of the quirks of the DB, maybe that is because they are one train for the API (ICE 532/ICE 782).

It wasn´t apparend, that the whole second train is missing and i thought it was a bug. Maybe you could somehow mark the second train as missing, as it is not clearly written anywhere. The message "multiple carriages are missing" is crossed out on the missing train, but not on the train that should be coupled with the missing one.
