### ISSUE TITLE
Unbekannte Züge

### ISSUE THREAD

**Issue by robinio9999** [marudor/BahnhofsAbfahrten#557]
Es gibt manchmal Züge die in der Zugsuche nicht bekannt sind. Z. B. In Hildesheim alle nächtlichen S-Bahnen ohne Liniennummer. Wenn man auf den Fahrtverlauf drückt kommt die Meldung ,,unbekannter Zug". Das Problem tritt auch komischer Weise manchmal bei Ersatzzügen auf.

**Comment by marudor** [comment]
Der SBahn teil ist nicht nachvollziehbar, ich hab keine SBahn ohne Liniennummer in Hildesheim gefunden.

Bei Ersatzfahrten gilt das HAFAS einfach manchmal die Fahrt nicht kennt. Da kann ich nix machen.

Wenn du Beispiele hast für die SBahn gerne reopen.
