### ISSUE TITLE
Automatisches aktualisieren im Fahrtverlauf

### ISSUE THREAD

**Issue by robinio9999** [marudor/BahnhofsAbfahrten#558]
Ich würde mir eine Funktion wünschen dass sich die Seite auch automatisch aktualisiert, wenn man den Fahrtverlauf eines Zuges ausgewählt hat. Das funktioniert zur Zeit noch nicht.

**Comment by marudor** [comment]
Einstellungen -> autoUpdate in Sekunden einstellen, updated dann auch die details page, nicht nur die Abfahrten.
