### ISSUE TITLE
geoSearch disabled?

### ISSUE THREAD

**Issue by derwaldgeist** [marudor/BahnhofsAbfahrten#564]
We're using the geoSearch API 

https://marudor.de/api/stopPlace/v1/geoSearch

but realized that it now all of the sudden returns the following:

"Due to rate-limit unreliable, disabled"

Is there any chance to get this great feature back?! It is vital for our use-case.

**Comment by marudor** [comment]
Sorry, currently not possible. 
There is https://docs.marudor.de/#operation/Geo%20Station%20v1 which is a way worse search but can be used.

**Comment by derwaldgeist** [comment]
This is very sad. Is there any chance to reactivate this API in the future?

**Comment by marudor** [comment]
If I find a non rate limited way for the underlying DB API.
I can't really cache geo station results.

**Comment by derwaldgeist** [comment]
Ok, will try if the other API fits our needs. But it would be awesome if the previous one could be re-activated some how.

**Comment by marudor** [comment]
@derwaldgeist It's back. (Hopefully stays now, obviously I can't promise that)

**Comment by derwaldgeist** [comment]
Hey @marudor, Thanks you so much for that info, highly appreciated!
