### ISSUE TITLE
Mobil ist der "Details" Button zu klein 

### ISSUE THREAD

**Issue by 1110101** [marudor/BahnhofsAbfahrten#572]
**Is your feature request related to a problem? Please describe.**
Der "Details" Button ist in der mobilen Ansicht sehr klein und man muss schon genau darauf achten diesen zu treffen und nicht doch auf den travelnyx Button zu kommen.

**Describe the solution you'd like**
Mir würden verschiedene Lösungen einfallen:
- Travelnyx Button via Einstellungen ausblendbar machen
- Den Details Buttton vergrößern
- Den Zugnamen ("RE 1") anklickbar machen

**Additional context**
Siehe "Details" Button Mitte Links.
![Screenshot_2022-02-19-14-46-08-127_com chrome beta](https://user-images.githubusercontent.com/6941073/154803464-5cba7060-20bd-4123-a2f2-3b151431f95d.jpg)

**Comment by marudor** [comment]
Details text jetzt größer.
Travelynx lässt sich außerdem verstecken.

Die Idee den Zugtext klickbar zu machen find ich prinzipiell gut, muss ich mir aber noch durch den Kopf gehen lassen.

**Comment by 1110101** [comment]
Vielen lieben Dank für die super schnelle Änderung 👍👍

**Comment by 1110101** [comment]
Ich kann gerne einen PR machen, aber bin mir bei den Tests nicht sicher.
