### ISSUE TITLE
Filter train types when Searching

### ISSUE THREAD

**Issue by Scroogeee** [marudor/BahnhofsAbfahrten#584]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to take trains like the ICE 4 or certain ICE 3 (Velaro + modernized) because I find the seats uncomfortable.

**Describe the solution you'd like**
I would like to be able to select/deselect train types like S, RB, RE, IC, ICE when using the routing feature (similar to what already exists in the DB routing), but also have an option to turn on "advanced settings" where I can also specifically select and deselect ICE (and IC?) train types. (or other trains where the data says which kind of train it is)

**Describe alternatives you've considered**
"Normal" usage of the marudor routing tool and manually sorting out the "uncomfortable" trains (= current implementation)

**Additional context**
Here's a screenshot of how the first part of my feature request looks like in the DB routing tool:

<img width="925" alt="image of the db selection screen" src="https://user-images.githubusercontent.com/30441849/162411240-55ce6035-2aa2-45cb-bed9-83754d6cb72f.png">

For the specialized train type selection, a similar UI layout could be used. The backend functinality should already be implemented as the website can already display the different ICE train types.

**Comment by marudor** [comment]
I can only implement the same filter bahn.de has.
Filtering by type would require me to implement my own routing. And thats 100% out of scope.
Would the same filter bahn.de has help you as well?

**Comment by Scroogeee** [comment]
The filter from bahn.de cannot discern different ICE types.

Why couldn't the routing from DB be used and then (locally) filter out all connections that contain certain specified train types (like 4 or 3V)? In my (very uninformed ;) view this should be able to be done because the ICE train type is already displayed, and thus queried.

**Comment by marudor** [comment]
Thats not how routing works.
You will never see a lot of connections that way. The only real solution is to never consider those trains while routing. Thats not possible without implementing a routing algorithm. As bahn.de based filering is not helping I'm closing this.

**Comment by Scroogeee** [comment]
Ok. Thanks though for the consideration of the feature request.
Do you happen to know where I could request for Bahn themselves to implement this?
