### ISSUE TITLE
Show operator of trains

### ISSUE THREAD

**Issue by TechMoritz** [marudor/BahnhofsAbfahrten#60]
It would be nice to see the operator for a specific train (e.g. "DB Regio NRW", "DB Fernverkehr", "GoAhead Baden-Württemberg"). The DB Navigator provides this information, so maybe there's an API for that.

**Comment by marudor** [comment]
Possible for Details & Routing.
Any Idea where to show that? Currently I can't see where it would fit.

**Comment by TechMoritz** [comment]
These are my ideas:

![image](https://user-images.githubusercontent.com/23395732/75112815-da199d80-5647-11ea-8273-e2cfdd33a74b.png)

![image](https://user-images.githubusercontent.com/23395732/75112847-3f6d8e80-5648-11ea-8231-4273fb346b8d.png)

![image](https://user-images.githubusercontent.com/23395732/75112896-e520fd80-5648-11ea-8b59-f6337c0cfa85.png)
