### ISSUE TITLE
Wagentyp resets itself

### ISSUE THREAD

**Issue by DerChaot** [marudor/BahnhofsAbfahrten#602]
**Describe the bug**
The Wagentyp setting is not saved as a cookie and gets reset after reloading the page.

**To Reproduce**
1. set Wagentyp to on
2. See the Wagentyp
3. Reload page using F5

**Expected behavior**
The setting should be carried over to the next reload, like all the other settings.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.5
 - Browser Safari 

**Additional context**

**Comment by marudor** [comment]
Looks like I may have forgotten the part that actually ready the cookie :D My bad, will be fixed soon.

**Comment by DerChaot** [comment]
Thank you ;P, refreshing is usable again
