### ISSUE TITLE
Eine Planung der Route nach Ankunftszeit wäre schön

### ISSUE THREAD

**Issue by daddyschlumpf** [marudor/BahnhofsAbfahrten#608]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by daddyschlumpf** [comment]
Hallo, ich hab es zumindest nicht gefunden: eine Routenplanung mit Angabe der Ankunftszeit (bleibt bisher nur das DB Navigator "Ding". Gibt es eine Erklärung  der Symbolbedeutungen? Grüner Haken lässt sich als "normal" oder "nicht überbesetzt" schließen, die anderen Symbole oder Einfärbungen, z.B. der Wagenklasse kann ich nicht verstehen-muss raten.
Das ist "meckern" auf hohem Niveau-das Programm begeistert mich. Danke.

**Comment by DerChaot** [comment]
Die Legende für diese Symbole kannst du definitiv unter den Abfahrten eines Bahnhofes sehen. Der grüne Haken folgt der Symbolik der Bahn. Es gibt noch gelb, orange und ausgebucht. Im Navigator ist das doch mit den drei Figuren dargestellt und zeigt die Auslastung. Bis zur Hälfte der Auslastung ist es glaube ich grün. Evtl. wird es auch bis zum ersten Drittel grün dargestellt.

**Comment by marudor** [comment]
Bezogen rein auf header und den ersten Satz (Bitte in Zukunft nichts mischen, ein issue pro Thema) ists ne gute Idee.
Also angabe von Ankunftszeit zum routen statt nur startzeit.

**Comment by daddyschlumpf** [comment]
Hallo, ja genauso war es gedacht. Danke für die Antwort. Wenn man z.B. einen
Termin hat und spätestens z.B. in Koblenz sein muss, 

kann man so die ideale Verbindung finden. 

Ab jetzt nur ein Item-versprochen. Alles Gute-tolle App!!! 

Harald

> On 14.06.2022 11:02:41, marudor ***@***.***) wrote: 
> > Bezogen rein auf header und den ersten Satz (Bitte in Zukunft nichts
mischen, ein issue pro Thema) ists ne gute Idee.

> Also angabe von Ankunftszeit zum routen statt nur startzeit. 
> 
> -- 
> Reply to this email directly or view it on GitHub: 
>
https://github.com/marudor/BahnhofsAbfahrten/issues/608#issuecomment-1154912
518
