### ISSUE TITLE
Zugdetails zeigen keine geplanten Züge an

### ISSUE THREAD

**Issue by DerChaot** [marudor/BahnhofsAbfahrten#609]
**Describe the bug**
Die Zugsuche zeigt nicht länger an, welcher Zug dem Plan nach fahren soll und wie er halten soll, wenn man an einem anderen Tag, als dem heutigen schaut.

**To Reproduce**
1. Go to Zugdetails on a day past today
2. Click next to any station name
4. No planned train type =>See error

**Expected behavior**
Geplanter Zug, wie evtl. es im Plan auf Fernbahn steht.

**Additional context**
Hast du eigentlich auch den Zugtyp entfernt, der immer oben in den Zugdetails oder in Routing neben der ICE/IC Nummer stand und die Generation(1,2,3,T,4) angezeigt hat, und die Möglichkeit im Routing den Halteplan zu sehen, wenn man neben eine Station eines Zuges klickt? Wenn ja, warum?

**Comment by DerChaot** [comment]
![4872CC38-9ED8-4CA1-9138-34B3F9EBCBE2](https://user-images.githubusercontent.com/19267144/173538940-39b79f58-1c4d-4cc1-bb1b-3ae85ac3a314.jpeg)
![A76C9FB9-4BCA-4379-9EAA-38DE4F941EBF](https://user-images.githubusercontent.com/19267144/173538962-c7bf2920-1506-414b-9147-26359d170770.jpeg)
In den rot markierten Beriechen fehlt der beschriebene Typ (ICE1/2/3/4/T), wobei dort immer nur die Zahl oder eben T in Klammern stand.

Im grün markierten Bereich fehlt der Zug, welcher fahren soll. Also z.B. „ICE 785-planned“ mit der Anzeige der Bahnsteigmarkierungen A-Z, wie er vermutlich laut Plan stehen soll.

Ich weiß nicht mehr, ob man im Routing neben eine Station klicken konnte, um die Wagenreihung an diesem Bahnhof anzuzeigen, wie es auch in den Details eines Zuges geht.

Bei den ersten beiden Punkten bin ich mir sicher, dass beides vorhanden war. Wenn du noch mehr Bilder brauchst muss ich mal schauen, ob ich dazu was finde.

**Comment by DerChaot** [comment]
Gott sei Dank, ich dachte schon, dass ich wirr im Kopf bin. War das im roten Bereich beschriebene mal vorhanden? Ich sehe auf meinen Bildern, dass es wohl schon im Mai fehlte, aber ich war mir sicher es am Anfang des Jahres noch gesehen zu haben.

**Comment by marudor** [comment]
Der Grund ist übrigens auch klar. Es war Fahrplanwechsel am 10. (also Sonntag)

**Comment by DerChaot** [comment]
Das hatte ich fast vermutet. Ich hatte aber auch Bilder auf dem Handy, wo zumindest der Plantyp schon im Mai fehlte. Das wird dann wohl andere Gründe gehabt haben denke ich. Wenn es wieder läuft ist es ja auch egal, was war.

**Comment by marudor** [comment]
Planwagenreihung ist wieder da. Die Kurzdarstellung oben (das im roten) sollte eh schon länger überarbeitet werden, ich würd das Ticket zumachen.

**Comment by marudor** [comment]
Oh noch als Hinweis - die performance davon ist grade etwas doof. (1,5-2s für die Plandaten, für die Echtzeitdaten brauch ich <100ms)
Ich weiß noch nicht warum, habs aber aufm Schirm.
