### ISSUE TITLE
Reload-Button

### ISSUE THREAD

**Issue by bsq1** [marudor/BahnhofsAbfahrten#616]
I’m using BahnhofsAbfahrten on my iPhone with a link on my homescreen. In this case the browser doesn’t provide a reload-button.

I don’t know how many people outside use it in the same way but it would be nice to have the opinion to reload the page with a button or something like a swipe down to reload.

thanks a lot for your brilliant work!

**Comment by marudor** [comment]
Was missing on iPhones due to a bug, fixed.
