### ISSUE TITLE
fehlender Nahverkehr in Zugsuche

### ISSUE THREAD

**Issue by tciberlin** [marudor/BahnhofsAbfahrten#623]
Aktuell werden Züge des Nahverkehrs in der Zugsuche nicht angezeigt, egal ob der Schalter "Nur Fernverkehr" an oder ausgeschaltet ist. ![image](https://user-images.githubusercontent.com/3908961/175801699-17f820b8-ba29-4c08-9ed2-ee79b15d3866.jpeg)

![image](https://user-images.githubusercontent.com/3908961/175801703-cd10011a-b96e-4860-885f-93e3158adbcb.jpeg)

**Comment by marudor** [comment]
Dinge die passieren wenn man Nacht um 3 noch schnell was macht :D
