### ISSUE TITLE
Ankunft Abfahrt mit Echtzeitdaten, neben der Ursprungs Ankunft/Abfahrt

### ISSUE THREAD

**Issue by Bosberus** [marudor/BahnhofsAbfahrten#625]
Die Möglichkeit neben der ursprünglichen Ankunft/Abfahrt auch die nun Aktuelle Ankunft/Abfahrt (samt Verspätung) Anzuzeigen, ohne dafür im Menü umstellen zu müssen wäre sehr praktisch. Im Prinzip hat die PIA dieses Feature bereits genauso wie es auch hier nützlich wäre.

**Comment by marudor** [comment]
Gabs früher, wird aktuell nicht passieren.
