### ISSUE TITLE
SNCF support

### ISSUE THREAD

**Issue by PDesire** [marudor/BahnhofsAbfahrten#63]
SNCF support wäre vielleicht etwas tolles für die Nutzer die in Frankreich leben.

Als HAFAS Endpoint versuche ich mich grad an [https://sncf-maps.hafas.de/bin/maps-ng/mgate.exe](https://sncf-maps.hafas.de/bin/maps-ng/mgate.exe). 

Client: `{"id":"SNCF_LIVEMAP","type":"WEB","name":"webapp","l":"vs_webapp"}`

Auth: `{"type":"AID","aid":"hf7mcf9bv3nv8g5f"}`

Sample Request:
`curl 'https://sncf-maps.hafas.de/bin/maps-ng/mgate.exe?rnd=1571175266249' -H 'Connection: keep-alive' -H 'Origin: https://sncf-maps.hafas.de' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.50 Safari/537.36' -H 'DNT: 1' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://sncf-maps.hafas.de/maps-ng/?language=en_GB' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: de-DE,de;q=0.9,en-DE;q=0.8,en;q=0.7,en-US;q=0.6' --data-binary '{"id":"nrk8rrrgkawnxwww","ver":"1.18","lang":"eng","auth":{"type":"AID","aid":"hf7mcf9bv3nv8g5f"},"client":{"id":"SNCF_LIVEMAP","type":"WEB","name":"webapp","l":"vs_webapp"},"formatted":false,"svcReqL":[{"meth":"JourneyGeoPos","req":{"rect":{"llCrd":{"x":-2746582.0312500005,"y":41360318.66306708},"urCrd":{"x":11447753.906250002,"y":53186287.573913306}},"perSize":35000,"perStep":10000,"trainPosMode":"REPORT_ONLY","jnyFltrL":[{"type":"INFOTEXTS","mode":"INC","value":"CT|INTERNATIONAL"},{"type":"INFOTEXTS","mode":"INC","value":"CT|TGV"},{"type":"INFOTEXTS","mode":"INC","value":"CT|INTERCITE"}],"getUnmatched":true,"date":"20191015","time":"233430"},"id":"1|18|"}]}' --compressed`

Ich selbst versuche das grad in den public-transport-enabler einzubauen, leider noch ohne Erfolg :(

Die Daten, etc. habe ich alle aus: [https://sncf-maps.hafas.de/maps-ng/?language=en_GB](https://sncf-maps.hafas.de/maps-ng/?language=en_GB)

**Comment by derhuerst** [comment]
> SNCF support wäre vielleicht etwas tolles für die Nutzer die in Frankreich leben.
>
> Als HAFAS Endpoint versuche ich mich grad an https://sncf-maps.hafas.de/bin/maps-ng/mgate.exe.

Hat der Endpoint denn Verkehrsdaten? http://sncf-maps.hafas.de/maps-ng/ zeigt mir keine Verbindungen.

cc @juliuste

**Comment by marudor** [comment]
Keine Verkehrsdaten -> kein support
