### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by christian179717** [marudor/BahnhofsAbfahrten#638]
Könntest du dir vorstellen, zusätzlich zur WebApp eine mobile App also eine .apk herauszubringen?

Das wäre gerade zur häufigen Nutzung einfacher.

Wäre sehr cool, wenn du das machen könntest.

**Comment by marudor** [comment]
Nein, ist eine PWA, einfach website zum homescreen hinzufügen, ist dann wie ne app.
