### ISSUE TITLE
sometimes to find the fastest route it is necessary to choose a stop that is on the shortest way as a stopover.

### ISSUE THREAD

**Issue by pt1997** [marudor/BahnhofsAbfahrten#65]
**Is your feature request related to a problem? Please describe.**
sometimes you will find the fastest route only if you choose a stop that is on the shortest way as a stopover. A example for this would be the route from "Freiburg(Breisgau) Hbf" to "Sommerbergstraße/EGT, Schonach im Schwarzwald" on weekends, if you add Elzach as an stopover you find routes that are about 1h faster. It's currently impossible to find that route if you don't know that it exists.

**Describe the solution you'd like**
maybe it is possible to add the stopover function from "reiseauskunft.bahn.de" to your site and detect and memorize faster routes that are found by users.

**Additional context**
I have reported this to DB twice but haven't revived any replies.

**Comment by marudor** [comment]
I won't build a custom routing => not in the scope of this project.
