### ISSUE TITLE
Falsche Einträge bei Abfahrtstafel. 

### ISSUE THREAD

**Issue by hellsi01** [marudor/BahnhofsAbfahrten#654]
Wenn man sich die Abfahrten/Ankünfte für Budapest-keleti bzw. Budapest-Kelenföld anzeigen lässt, erscheinen in der Übersicht auch die Abfahrten/Ankünfte für den jeweils anderen Bahnhof.

Situation tritt auf unter Android Firefox 103.2, andere Browser/OS nicht getestet. 

![Screenshot_20220813_113812_org mozilla firefox](https://user-images.githubusercontent.com/97510151/184478370-7c16316d-5a4f-4a93-8e26-95b934a2b4df.jpg)

**Comment by marudor** [comment]
Orr schon wieder so ein Fall...
Ich weiß worans liegt und kanns demnächst mal fixen. Hab ich für irgend eine Haltestelle schon mal gemacht :D
