### ISSUE TITLE
Implementation of new DB API due to problems of displayment for regional traffic

### ISSUE THREAD

**Issue by Gegreenpeaced** [marudor/BahnhofsAbfahrten#656]
**Describe the bug**
Mit der neuen Bahn API funktioniert die Abfrage zum Regionalverkehr nicht mehr.

**To Reproduce**
Einfach mal nach Abfahrten bei einer Station suchen wo es nur Regionalverkehr gibt. (BSP: Stralsund)

**Expected behavior**
Anzeige von Regionalzügen

**Desktop (please complete the following information):**
 - OS: Windows 10 NT 1052
 - Browser: Chrome
 - Version: 104.0.5112.81

**Additional context**
Neues Open Data Portal müsste vermutlich eingebunden werden und ein paar Dinge getauscht werden: https://developers.deutschebahn.com/db-api-marketplace/apis/

**Comment by marudor** [comment]
Bitte ein ganz konkretes Beispiel. Ich kann hieraus nichts nachvollziehen. Funktioniert einwndfrei mit Regionalverkehr only Haltestellen.

**Comment by Gegreenpeaced** [comment]
Alles klar, kein Problem

Ich habe die Website aufgerufen und bekomme in Sassnitz keine Abfahrten angezeigt, obwohl es welche gibt.
https://marudor.de/Sassnitz

**Comment by marudor** [comment]
Hast du einen Filter drin?
Ich seh da den RE9 fahren.

**Comment by marudor** [comment]
Habs aber zum anlass genommen die Nachricht zu ändern.
Falls die Abfahrten durch die filter leer sind wird drauf hingewiesen.
