### ISSUE TITLE
Allowing DS100-Shortcodes to be used in the search

### ISSUE THREAD

**Issue by BadWolf97** [marudor/BahnhofsAbfahrten#662]
**Is your feature request related to a problem? Please describe.**
Unfortuanately, it's not possible to search with DS100 Shortcodes. This would be an easier way than typing the whole station name

**Describe the solution you'd like**
The search should search with DS100 Shortcodes too

**Additional context**
A list of DS100 Shortcodes can be found here: https://fahrweg.dbnetze.com/resource/blob/1359908/f9d782b88f2c1224ac1192e2d4b5f6ff/betriebsstellen-data.pdf

**Comment by marudor** [comment]
It's already possible.

**Comment by BadWolf97** [comment]
That's wrong at least in self hosting this repository. I use the latest version on my server.

For example:
https://dba.fphst.de/DD
creates the Page for Dresden HBF.
DD is Dresden Dobritz.
