### ISSUE TITLE
Zugauslastung fehlt

### ISSUE THREAD

**Issue by DerChaot** [marudor/BahnhofsAbfahrten#691]
**Describe the bug**
Die Zugauslastungsanzeige fehlt komplett. Sowohl bei den Abfahrten, als auch Zugsuche.

**To Reproduce**
1. Go to Abfahrten
2. Click on Any train
3. See error

**Expected behavior**
Eine Anzeige nach dem alten Schema mit grün/gelb/orange/roten Symbolen

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version 

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS16.0.3
 - Browser safari

**Additional context**

**Comment by marudor** [comment]
Schon aufgefallen. Liegt vermutlich am HAFAS?
Ich schau mal rein.

**Comment by DerChaot** [comment]
Kein Stress. Gestern dauerte das sehr lange, bis die Anzeige kam. Nun wie du weißt garnicht.

**Comment by DerChaot** [comment]
Kein Stress. Gestern dauerte das sehr lange, bis die Anzeige kam. Nun wie du weißt garnicht.

**Comment by marudor** [comment]
Funktioniert im Navigator auch nicht. Problem bei HAFAS. Ich schliess das mal da ich annehme das ich nichts machen muss sondern HAFAS das fixen muss.

**Comment by DerChaot** [comment]
Ja über den gesamten Verlauf zeigt der Navigator das aktuell nicht an, sondern nur entlang der ausgewählten Route/Reise.

**Comment by marudor** [comment]
Bei mir gehts garnicht. Hast du nen Beispiel wo es teilweise geht?

**Comment by DerChaot** [comment]
![16594A36-597E-43E6-85FC-E3CD34CBCC3E](https://user-images.githubusercontent.com/19267144/199183562-3f4af2de-50b4-466e-9297-1dd8b7c16da8.png)
![5D94DA7F-BBC9-4D75-86F7-F942DF0A29ED](https://user-images.githubusercontent.com/19267144/199183572-09690176-b4e2-429f-8712-cc71effca5e8.png)
![AE9B147C-7B6F-4A9B-B27B-0E27D2B40240](https://user-images.githubusercontent.com/19267144/199183580-7b246788-3509-4646-8026-2ff82f6b6fb4.png)

**Comment by marudor** [comment]
Geht bei mir nicht.
Ich vermute caching. Also dein Client hat das noch gecached für den Abschnitt, darum gehts auch nur im Abschnitt und nicht für die gesamte Fahrt.

**Comment by DerChaot** [comment]
![5F6AA3AD-02DC-4281-8E46-F00B39A5260F](https://user-images.githubusercontent.com/19267144/199184775-35f16c1c-e6bb-47c9-814e-50e23dbbf881.png)
![09B2A0EA-32C8-4B48-B677-5687A7613BC4](https://user-images.githubusercontent.com/19267144/199184776-97212dbc-7cc4-4854-9839-bc39829fa93e.png)
Bist du dir sicher? Ich habe das vorher nie aufgerufen und diese Strecke, die ich nie fahre und welche auch erst am Freitag stattfindet, kann dich nicht auch gecached sein.

**Comment by marudor** [comment]
AH. Du nutzt den DB Next Navigator?
Da gehts bei mir genauso wie bei dir.
Im normalen gehts garnicht

**Comment by DerChaot** [comment]
Ja den nutze ich. Interessant, dann heißt es wohl abwarten.

**Comment by marudor** [comment]
Ja, da kann ich leider auch nicht trivial nachschauen. (Certificate Pinning)
