### ISSUE TITLE
Bei der Unteranwendung "Zugläufe" lässt sich auf dem Touchscreen nicht nach Baureihen filtern

### ISSUE THREAD

**Issue by ValentinJns** [marudor/BahnhofsAbfahrten#698]
Bei der Unteranwendung "Zugläufe" lässt sich auf dem Touchscreen nicht nach Baureihen filtern

**Smartphone (please complete the following information):**
 - Device: Huawei P30 mit Google
 - OS: Android 10
 - Browser Chrome

**Comment by marudor** [comment]
Seite ist nur für desktop useable aktuell. Wont fix
