### ISSUE TITLE
Verspätung nicht immer eingerechnet.

### ISSUE THREAD

**Issue by omia** [marudor/BahnhofsAbfahrten#84]
**Describe the bug**
Die Verspätung wurde bei einem Bf nicht mit eingerechnet.

**To Reproduce**
Ähm keine Ahnung. (Ich weiß das das nicht hilfreich ist.)
Aber auch neu laden hat das Problem nicht gelöst.
Wenn der Zug an der  Haltestelle war stimmte die Anzeige wieder

**Expected behavior**
Die Verspätung sollte bei allen Uhrzeiten eingerechnet werden.
**Screenshots**
![Screenshot_20191022-173754](https://user-images.githubusercontent.com/7889102/67305957-7bf07880-f4f6-11e9-92b0-c4af8bbe63d5.png)

**Smartphone (please complete the following information):**
 - Device: pixel 2
 - OS: Android 10
 - Browser chrome
 - Version 80.0

**Comment by marudor** [comment]
Ist eingerechnet. Hier ist das Problem Differenz HAFAS / IRIS.
Der nächste Halt (Hier Lemförde) Wird aus dem IRIS genommen statt dem HAFAS.
Scheinbar haben die beiden hier andere Daten => Wird falsch angezeigt.

Ich muss mir das mal anschauen und evtl doch beim HAFAS bleiben als quelle für die page.
